// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedef/game_def.proto

/*
Package gamedef is a generated protocol buffer package.

It is generated from these files:
	gamedef/game_def.proto

It has these top-level messages:
	LoginInfo
	Account
	ExtraAccountInfo
	User
	Individual
	General
	Item
	UserData
	Buff
	Chess
*/
package gamedef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gameconf "github.com/wenxiu2199/gameserver/src/server/gameproto/gameconf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ===================================
type ChessTyp int32

const (
	ChessTyp_CTInvalid ChessTyp = 0
	ChessTyp_CTBlank   ChessTyp = 1
	ChessTyp_CTMine    ChessTyp = 2
)

var ChessTyp_name = map[int32]string{
	0: "CTInvalid",
	1: "CTBlank",
	2: "CTMine",
}
var ChessTyp_value = map[string]int32{
	"CTInvalid": 0,
	"CTBlank":   1,
	"CTMine":    2,
}

func (x ChessTyp) String() string {
	return proto.EnumName(ChessTyp_name, int32(x))
}
func (ChessTyp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 用户登录信息
type LoginInfo struct {
	Ip     string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Region string `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
}

func (m *LoginInfo) Reset()                    { *m = LoginInfo{} }
func (m *LoginInfo) String() string            { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()               {}
func (*LoginInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LoginInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type Account struct {
	Account string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	UserID  uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Account) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Account) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// 账号额外信息
type ExtraAccountInfo struct {
	AccountType uint32 `protobuf:"varint,1,opt,name=accountType" json:"accountType,omitempty"`
	Channel     uint32 `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	Platform    uint32 `protobuf:"varint,3,opt,name=platform" json:"platform,omitempty"`
	Ip          string `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
	Account     string `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *ExtraAccountInfo) Reset()                    { *m = ExtraAccountInfo{} }
func (m *ExtraAccountInfo) String() string            { return proto.CompactTextString(m) }
func (*ExtraAccountInfo) ProtoMessage()               {}
func (*ExtraAccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExtraAccountInfo) GetAccountType() uint32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *ExtraAccountInfo) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *ExtraAccountInfo) GetPlatform() uint32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *ExtraAccountInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ExtraAccountInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// 用户信息
type User struct {
	UserID   uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	SexID    uint32 `protobuf:"varint,3,opt,name=sexID" json:"sexID,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *User) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetSexID() uint32 {
	if m != nil {
		return m.SexID
	}
	return 0
}

type Individual struct {
	Hp        int32 `protobuf:"varint,1,opt,name=hp" json:"hp,omitempty"`
	Attack    int32 `protobuf:"varint,2,opt,name=attack" json:"attack,omitempty"`
	Defense   int32 `protobuf:"varint,3,opt,name=defense" json:"defense,omitempty"`
	SpAttack  int32 `protobuf:"varint,4,opt,name=spAttack" json:"spAttack,omitempty"`
	SpDefense int32 `protobuf:"varint,5,opt,name=spDefense" json:"spDefense,omitempty"`
	Speed     int32 `protobuf:"varint,6,opt,name=speed" json:"speed,omitempty"`
}

func (m *Individual) Reset()                    { *m = Individual{} }
func (m *Individual) String() string            { return proto.CompactTextString(m) }
func (*Individual) ProtoMessage()               {}
func (*Individual) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Individual) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *Individual) GetAttack() int32 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *Individual) GetDefense() int32 {
	if m != nil {
		return m.Defense
	}
	return 0
}

func (m *Individual) GetSpAttack() int32 {
	if m != nil {
		return m.SpAttack
	}
	return 0
}

func (m *Individual) GetSpDefense() int32 {
	if m != nil {
		return m.SpDefense
	}
	return 0
}

func (m *Individual) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

// 武将信息
type General struct {
	PkID       uint64      `protobuf:"varint,1,opt,name=pkID" json:"pkID,omitempty"`
	GeneralID  uint32      `protobuf:"varint,2,opt,name=generalID" json:"generalID,omitempty"`
	Individual *Individual `protobuf:"bytes,3,opt,name=individual" json:"individual,omitempty"`
	Effort     *Individual `protobuf:"bytes,4,opt,name=effort" json:"effort,omitempty"`
	Skills     []uint32    `protobuf:"varint,5,rep,packed,name=skills" json:"skills,omitempty"`
	Level      uint32      `protobuf:"varint,6,opt,name=level" json:"level,omitempty"`
}

func (m *General) Reset()                    { *m = General{} }
func (m *General) String() string            { return proto.CompactTextString(m) }
func (*General) ProtoMessage()               {}
func (*General) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *General) GetPkID() uint64 {
	if m != nil {
		return m.PkID
	}
	return 0
}

func (m *General) GetGeneralID() uint32 {
	if m != nil {
		return m.GeneralID
	}
	return 0
}

func (m *General) GetIndividual() *Individual {
	if m != nil {
		return m.Individual
	}
	return nil
}

func (m *General) GetEffort() *Individual {
	if m != nil {
		return m.Effort
	}
	return nil
}

func (m *General) GetSkills() []uint32 {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *General) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type Item struct {
	PkID   uint64 `protobuf:"varint,1,opt,name=pkID" json:"pkID,omitempty"`
	ItemID uint32 `protobuf:"varint,2,opt,name=itemID" json:"itemID,omitempty"`
	Num    uint32 `protobuf:"varint,3,opt,name=num" json:"num,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Item) GetPkID() uint64 {
	if m != nil {
		return m.PkID
	}
	return 0
}

func (m *Item) GetItemID() uint32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *Item) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type UserData struct {
	User     *User      `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Generals []*General `protobuf:"bytes,2,rep,name=generals" json:"generals,omitempty"`
	Items    []*Item    `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
}

func (m *UserData) Reset()                    { *m = UserData{} }
func (m *UserData) String() string            { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()               {}
func (*UserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserData) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserData) GetGenerals() []*General {
	if m != nil {
		return m.Generals
	}
	return nil
}

func (m *UserData) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// ===============Game数据====================
type Buff struct {
	BuffType gameconf.SkillEffectTyp `protobuf:"varint,1,opt,name=buffType,enum=gameconf.SkillEffectTyp" json:"buffType,omitempty"`
	Last     uint32                  `protobuf:"varint,2,opt,name=last" json:"last,omitempty"`
}

func (m *Buff) Reset()                    { *m = Buff{} }
func (m *Buff) String() string            { return proto.CompactTextString(m) }
func (*Buff) ProtoMessage()               {}
func (*Buff) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Buff) GetBuffType() gameconf.SkillEffectTyp {
	if m != nil {
		return m.BuffType
	}
	return gameconf.SkillEffectTyp_SETInvliad
}

func (m *Buff) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type Chess struct {
	ChessType ChessTyp `protobuf:"varint,1,opt,name=chessType,enum=gamedef.ChessTyp" json:"chessType,omitempty"`
	Visible   bool     `protobuf:"varint,2,opt,name=visible" json:"visible,omitempty"`
	MineNum   uint32   `protobuf:"varint,3,opt,name=mineNum" json:"mineNum,omitempty"`
}

func (m *Chess) Reset()                    { *m = Chess{} }
func (m *Chess) String() string            { return proto.CompactTextString(m) }
func (*Chess) ProtoMessage()               {}
func (*Chess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Chess) GetChessType() ChessTyp {
	if m != nil {
		return m.ChessType
	}
	return ChessTyp_CTInvalid
}

func (m *Chess) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Chess) GetMineNum() uint32 {
	if m != nil {
		return m.MineNum
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginInfo)(nil), "gamedef.LoginInfo")
	proto.RegisterType((*Account)(nil), "gamedef.Account")
	proto.RegisterType((*ExtraAccountInfo)(nil), "gamedef.ExtraAccountInfo")
	proto.RegisterType((*User)(nil), "gamedef.User")
	proto.RegisterType((*Individual)(nil), "gamedef.Individual")
	proto.RegisterType((*General)(nil), "gamedef.General")
	proto.RegisterType((*Item)(nil), "gamedef.Item")
	proto.RegisterType((*UserData)(nil), "gamedef.UserData")
	proto.RegisterType((*Buff)(nil), "gamedef.Buff")
	proto.RegisterType((*Chess)(nil), "gamedef.Chess")
	proto.RegisterEnum("gamedef.ChessTyp", ChessTyp_name, ChessTyp_value)
}

func init() { proto.RegisterFile("gamedef/game_def.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x41, 0x8f, 0xda, 0x3a,
	0x10, 0x7e, 0x01, 0x12, 0x60, 0x50, 0x56, 0x3c, 0xbf, 0x27, 0x14, 0xad, 0x7a, 0xa0, 0xe9, 0x65,
	0xd5, 0x56, 0xa0, 0xb2, 0xbd, 0xac, 0x7a, 0xda, 0x85, 0x55, 0x85, 0xd4, 0xae, 0x2a, 0x97, 0x9e,
	0x2b, 0x93, 0x4c, 0xc0, 0x22, 0x71, 0xa2, 0x38, 0xa1, 0xbb, 0xb7, 0xfe, 0x88, 0x9e, 0xfb, 0x87,
	0xfa, 0xa7, 0x2a, 0x3b, 0x8e, 0xe1, 0xd0, 0x9e, 0x98, 0xcf, 0x33, 0xf3, 0xf9, 0xfb, 0x26, 0x63,
	0x60, 0xb2, 0x63, 0x19, 0xc6, 0x98, 0xcc, 0xd5, 0xef, 0xd7, 0x18, 0x93, 0x59, 0x51, 0xe6, 0x55,
	0x4e, 0xfa, 0xe6, 0xfc, 0xf2, 0x61, 0xc7, 0xab, 0x7d, 0xbd, 0x9d, 0x45, 0x79, 0x36, 0xff, 0x86,
	0xe2, 0x91, 0xd7, 0x8b, 0x37, 0x37, 0x37, 0xba, 0x5c, 0x62, 0x79, 0xc4, 0x72, 0x2e, 0xcb, 0x68,
	0x6e, 0x42, 0x75, 0xaa, 0xfb, 0x75, 0x14, 0xe5, 0xc2, 0xf0, 0x56, 0x4f, 0x05, 0x36, 0xc4, 0xe1,
	0x35, 0x0c, 0x3f, 0xe4, 0x3b, 0x2e, 0xd6, 0x22, 0xc9, 0xc9, 0x05, 0x74, 0x78, 0x11, 0x38, 0x53,
	0xe7, 0x6a, 0x48, 0x3b, 0xbc, 0x20, 0x13, 0xf0, 0x4a, 0xdc, 0xf1, 0x5c, 0x04, 0x1d, 0x7d, 0x66,
	0x50, 0xf8, 0x0e, 0xfa, 0xb7, 0x51, 0x94, 0xd7, 0xa2, 0x22, 0x81, 0x0d, 0x4d, 0x9f, 0xcd, 0x4c,
	0xc0, 0xab, 0x25, 0x96, 0xeb, 0x95, 0x6e, 0xee, 0x51, 0x83, 0xc2, 0x1f, 0x0e, 0x8c, 0xef, 0x1f,
	0xab, 0x92, 0x99, 0x42, 0x7d, 0xf3, 0x14, 0x46, 0xac, 0x81, 0x9b, 0xa7, 0x02, 0x35, 0x95, 0x4f,
	0xcf, 0x8f, 0xd4, 0x45, 0xd1, 0x9e, 0x09, 0x81, 0xa9, 0xe6, 0xf3, 0x69, 0x0b, 0xc9, 0x25, 0x0c,
	0x8a, 0x94, 0x55, 0x49, 0x5e, 0x66, 0x41, 0x57, 0xa7, 0x2c, 0x36, 0x8e, 0x7a, 0xd6, 0x51, 0x00,
	0x7d, 0x43, 0x1a, 0xb8, 0x8d, 0x5c, 0x03, 0xc3, 0x4f, 0xd0, 0xfb, 0x22, 0xb1, 0x3c, 0x93, 0xed,
	0x9c, 0xcb, 0x56, 0xb7, 0x08, 0x1e, 0x1d, 0x04, 0xcb, 0xd0, 0x4c, 0xc3, 0x62, 0xf2, 0x3f, 0xb8,
	0x12, 0x1f, 0xd7, 0x2b, 0x73, 0x7d, 0x03, 0xc2, 0x9f, 0x0e, 0xc0, 0x5a, 0xc4, 0xfc, 0xc8, 0xe3,
	0x9a, 0xa5, 0x4a, 0xca, 0xbe, 0x19, 0xae, 0x4b, 0x3b, 0x7b, 0x3d, 0x5c, 0x56, 0x55, 0x2c, 0x3a,
	0x68, 0x3a, 0x97, 0x1a, 0xa4, 0x24, 0xc6, 0x98, 0xa0, 0x90, 0xa8, 0xe9, 0x5c, 0xda, 0x42, 0x25,
	0x41, 0x16, 0xb7, 0x4d, 0x4f, 0x4f, 0xa7, 0x2c, 0x26, 0xcf, 0x60, 0x28, 0x8b, 0x95, 0xe9, 0x73,
	0x75, 0xf2, 0x74, 0xa0, 0x05, 0x16, 0x88, 0x71, 0xe0, 0xe9, 0x4c, 0x03, 0xc2, 0x5f, 0x0e, 0xf4,
	0xdf, 0xa3, 0xc0, 0x92, 0xa5, 0x84, 0x40, 0xaf, 0x38, 0x58, 0xd3, 0x3a, 0x56, 0x9c, 0xbb, 0x26,
	0x6d, 0x3e, 0xa2, 0x4f, 0x4f, 0x07, 0xe4, 0x1a, 0x80, 0x5b, 0x77, 0x5a, 0xea, 0x68, 0xf1, 0xdf,
	0xcc, 0xec, 0xe9, 0xec, 0x64, 0x9c, 0x9e, 0x95, 0x91, 0x57, 0xe0, 0x61, 0x92, 0xe4, 0x65, 0xa5,
	0x0d, 0xfc, 0xa5, 0xc1, 0x94, 0xa8, 0x09, 0xc9, 0x03, 0x4f, 0x53, 0x19, 0xb8, 0xd3, 0xee, 0x95,
	0x4f, 0x0d, 0x52, 0x6e, 0x52, 0x3c, 0x62, 0xaa, 0xdd, 0xf8, 0xb4, 0x01, 0xe1, 0x0a, 0x7a, 0xeb,
	0x0a, 0xb3, 0x3f, 0x3a, 0x99, 0x80, 0xc7, 0x2b, 0xcc, 0xac, 0x0d, 0x83, 0xc8, 0x18, 0xba, 0xa2,
	0x6e, 0xb7, 0x46, 0x85, 0xe1, 0x77, 0x07, 0x06, 0x6a, 0x0f, 0x56, 0xac, 0x62, 0xe4, 0x39, 0xf4,
	0xd4, 0xd7, 0xd7, 0x54, 0xa3, 0x85, 0x6f, 0xb5, 0xaa, 0x02, 0xaa, 0x53, 0xe4, 0x35, 0x0c, 0xcc,
	0x48, 0x64, 0xd0, 0x99, 0x76, 0xaf, 0x46, 0x8b, 0xb1, 0x2d, 0x33, 0xb3, 0xa5, 0xb6, 0x82, 0xbc,
	0x00, 0x57, 0xdd, 0x2c, 0x83, 0xae, 0x2e, 0x3d, 0x31, 0x2a, 0xe5, 0xb4, 0xc9, 0xa9, 0x4d, 0xbc,
	0xab, 0x93, 0x84, 0xbc, 0x85, 0xc1, 0xb6, 0x4e, 0x12, 0xfb, 0x20, 0x2e, 0x16, 0xc1, 0xac, 0x7d,
	0xc7, 0xb3, 0xcf, 0x6a, 0x14, 0xf7, 0x49, 0x82, 0x91, 0x7a, 0x1e, 0xd4, 0x56, 0x2a, 0xfb, 0x29,
	0x93, 0x95, 0x31, 0xaa, 0xe3, 0x30, 0x05, 0x77, 0xb9, 0x47, 0x29, 0xc9, 0x1c, 0x86, 0x91, 0x0a,
	0xce, 0x38, 0xff, 0xb5, 0x1a, 0x96, 0x26, 0x43, 0x4f, 0x35, 0x6a, 0x19, 0x8f, 0x5c, 0xf2, 0x6d,
	0xda, 0x2c, 0xfd, 0x80, 0xb6, 0x50, 0x65, 0x32, 0x2e, 0xf0, 0xc1, 0x8e, 0xaf, 0x85, 0x2f, 0x17,
	0x30, 0x68, 0xa9, 0x88, 0x0f, 0xc3, 0xe5, 0x66, 0x2d, 0x8e, 0x2c, 0xe5, 0xf1, 0xf8, 0x1f, 0x32,
	0x82, 0xfe, 0x72, 0x73, 0x97, 0x32, 0x71, 0x18, 0x3b, 0x04, 0xc0, 0x5b, 0x6e, 0x3e, 0x72, 0x81,
	0xe3, 0xce, 0xd6, 0xd3, 0xff, 0x46, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x98, 0x68,
	0xbe, 0x00, 0x05, 0x00, 0x00,
}
