// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedef/game_def.proto

/*
Package gamedef is a generated protocol buffer package.

It is generated from these files:
	gamedef/game_def.proto

It has these top-level messages:
	LoginInfo
	Account
	ExtraAccountInfo
	User
*/
package gamedef

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户登录信息
type LoginInfo struct {
	Ip     string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Region string `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
}

func (m *LoginInfo) Reset()                    { *m = LoginInfo{} }
func (m *LoginInfo) String() string            { return proto.CompactTextString(m) }
func (*LoginInfo) ProtoMessage()               {}
func (*LoginInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LoginInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type Account struct {
	Account string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	UserID  uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Account) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Account) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// 账号额外信息
type ExtraAccountInfo struct {
	AccountType uint32 `protobuf:"varint,1,opt,name=accountType" json:"accountType,omitempty"`
	Channel     uint32 `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	Platform    uint32 `protobuf:"varint,3,opt,name=platform" json:"platform,omitempty"`
	Ip          string `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
	Account     string `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
}

func (m *ExtraAccountInfo) Reset()                    { *m = ExtraAccountInfo{} }
func (m *ExtraAccountInfo) String() string            { return proto.CompactTextString(m) }
func (*ExtraAccountInfo) ProtoMessage()               {}
func (*ExtraAccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExtraAccountInfo) GetAccountType() uint32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *ExtraAccountInfo) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *ExtraAccountInfo) GetPlatform() uint32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *ExtraAccountInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ExtraAccountInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// 用户信息
type User struct {
	XId      string `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	UserID   uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	SexID    uint32 `protobuf:"varint,4,opt,name=sexID" json:"sexID,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *User) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *User) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetSexID() uint32 {
	if m != nil {
		return m.SexID
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginInfo)(nil), "gamedef.LoginInfo")
	proto.RegisterType((*Account)(nil), "gamedef.Account")
	proto.RegisterType((*ExtraAccountInfo)(nil), "gamedef.ExtraAccountInfo")
	proto.RegisterType((*User)(nil), "gamedef.User")
}

func init() { proto.RegisterFile("gamedef/game_def.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x34, 0x4d, 0xc8, 0xa1, 0x00, 0xb2, 0x50, 0x64, 0x31, 0x55, 0x99, 0x98, 0x60,
	0xe8, 0xc8, 0x84, 0x54, 0x86, 0x48, 0x4c, 0x16, 0xcc, 0x95, 0x49, 0x2e, 0xc1, 0xa2, 0xb1, 0x2d,
	0x27, 0x95, 0xca, 0xff, 0xe0, 0x07, 0xa3, 0x5c, 0x5c, 0x8b, 0x85, 0xc9, 0xfe, 0xee, 0x7c, 0xef,
	0xf9, 0x1d, 0x94, 0xbd, 0x1c, 0xb0, 0xc5, 0xee, 0x71, 0x3e, 0xf7, 0x2d, 0x76, 0x0f, 0xd6, 0x99,
	0xc9, 0xb0, 0xcc, 0xd7, 0xab, 0x2d, 0xe4, 0xaf, 0xa6, 0x57, 0xba, 0xd6, 0x9d, 0x61, 0x57, 0x10,
	0x2b, 0xcb, 0xa3, 0x4d, 0x74, 0x9f, 0x8b, 0x58, 0x59, 0x56, 0x42, 0xea, 0xb0, 0x57, 0x46, 0xf3,
	0x98, 0x6a, 0x9e, 0xaa, 0x27, 0xc8, 0x9e, 0x9b, 0xc6, 0x1c, 0xf5, 0xc4, 0x78, 0xb8, 0xfa, 0xb9,
	0xd0, 0x29, 0x21, 0x3d, 0x8e, 0xe8, 0xea, 0x1d, 0x0d, 0x27, 0xc2, 0x53, 0xf5, 0x13, 0xc1, 0xcd,
	0xcb, 0x69, 0x72, 0xd2, 0x3f, 0x24, 0xe7, 0x0d, 0x5c, 0xca, 0x05, 0xdf, 0xbe, 0x2d, 0x92, 0x54,
	0x21, 0xfe, 0x96, 0x66, 0xa3, 0xe6, 0x53, 0x6a, 0x8d, 0x07, 0xd2, 0x2b, 0xc4, 0x19, 0xd9, 0x1d,
	0x5c, 0xd8, 0x83, 0x9c, 0x3a, 0xe3, 0x06, 0xbe, 0xa2, 0x56, 0x60, 0x9f, 0x28, 0x09, 0x89, 0x38,
	0x64, 0x5e, 0x94, 0xaf, 0x97, 0xef, 0x7a, 0xac, 0x24, 0x24, 0xef, 0x23, 0x3a, 0x76, 0x0d, 0xab,
	0xbd, 0x6a, 0xcf, 0x4b, 0xa8, 0xdb, 0xff, 0x72, 0xcc, 0xb6, 0x5a, 0x35, 0x5f, 0x5a, 0x0e, 0x48,
	0xb6, 0xb9, 0x08, 0xcc, 0x6e, 0x61, 0x3d, 0xe2, 0xa9, 0xde, 0x91, 0x73, 0x21, 0x16, 0xf8, 0x48,
	0x69, 0xf7, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x9b, 0x96, 0xcd, 0x95, 0x01, 0x00,
	0x00,
}
