// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smsg/gt_msg.proto

/*
Package smsg is a generated protocol buffer package.

It is generated from these files:
	smsg/gt_msg.proto

It has these top-level messages:
	GtLsReqAuth
	GtLsRespAuth
	SSGtNotifyMessage
*/
package smsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GtLsReqAuth struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *GtLsReqAuth) Reset()                    { *m = GtLsReqAuth{} }
func (m *GtLsReqAuth) String() string            { return proto.CompactTextString(m) }
func (*GtLsReqAuth) ProtoMessage()               {}
func (*GtLsReqAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GtLsReqAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GtLsReqAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GtLsRespAuth struct {
	ErrCode    uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg     string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	UserID     uint64 `protobuf:"varint,4,opt,name=userID" json:"userID,omitempty"`
	Sign       string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	UnlockTime int64  `protobuf:"varint,6,opt,name=unlockTime" json:"unlockTime,omitempty"`
}

func (m *GtLsRespAuth) Reset()                    { *m = GtLsRespAuth{} }
func (m *GtLsRespAuth) String() string            { return proto.CompactTextString(m) }
func (*GtLsRespAuth) ProtoMessage()               {}
func (*GtLsRespAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GtLsRespAuth) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GtLsRespAuth) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GtLsRespAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GtLsRespAuth) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GtLsRespAuth) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *GtLsRespAuth) GetUnlockTime() int64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

type SSGtNotifyMessage struct {
}

func (m *SSGtNotifyMessage) Reset()                    { *m = SSGtNotifyMessage{} }
func (m *SSGtNotifyMessage) String() string            { return proto.CompactTextString(m) }
func (*SSGtNotifyMessage) ProtoMessage()               {}
func (*SSGtNotifyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*GtLsReqAuth)(nil), "smsg.GtLsReqAuth")
	proto.RegisterType((*GtLsRespAuth)(nil), "smsg.GtLsRespAuth")
	proto.RegisterType((*SSGtNotifyMessage)(nil), "smsg.SSGtNotifyMessage")
}

func init() { proto.RegisterFile("smsg/gt_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x89, 0x2f, 0x46, 0x1d, 0x75, 0xf1, 0x22, 0x94, 0xe0, 0x42, 0x4a, 0x57, 0x5d, 0xe9,
	0xc2, 0x2f, 0x90, 0x0a, 0x45, 0xb0, 0x2e, 0x52, 0xf7, 0x52, 0xdb, 0x31, 0x16, 0x6d, 0x53, 0x33,
	0x09, 0xe2, 0x0f, 0xf9, 0x9d, 0x62, 0x6c, 0xa5, 0x6f, 0x37, 0xe7, 0xce, 0x70, 0x2e, 0x0c, 0x6c,
	0x69, 0x20, 0x73, 0x65, 0xfc, 0xd3, 0x40, 0xe6, 0x72, 0x72, 0xd6, 0x5b, 0xc9, 0x7f, 0xa3, 0xac,
	0x80, 0xe3, 0xd2, 0xdf, 0x93, 0xc6, 0x8f, 0x9b, 0xe0, 0x5f, 0xa5, 0x82, 0x83, 0xa6, 0x6d, 0x6d,
	0x18, 0xbd, 0x62, 0x29, 0xcb, 0x8f, 0xf4, 0x82, 0xf2, 0x1c, 0x0e, 0xa7, 0x86, 0xe8, 0xd3, 0xba,
	0x4e, 0xed, 0xc5, 0xd5, 0x3f, 0x67, 0xdf, 0x0c, 0x4e, 0xfe, 0x2c, 0x34, 0x2d, 0x1a, 0x74, 0xae,
	0xb0, 0x1d, 0x46, 0xcd, 0xa9, 0x5e, 0x50, 0x26, 0x20, 0xd0, 0xb9, 0x8a, 0xcc, 0x2c, 0x99, 0x69,
	0x5d, 0xbc, 0xd9, 0x2d, 0x4e, 0x40, 0x04, 0x42, 0x77, 0x77, 0xab, 0x78, 0xca, 0x72, 0xae, 0x67,
	0x92, 0x12, 0x38, 0xf5, 0x66, 0x54, 0xfb, 0xf1, 0x3c, 0xce, 0xf2, 0x02, 0x20, 0x8c, 0xef, 0xb6,
	0x7d, 0x7b, 0xec, 0x07, 0x54, 0x22, 0x65, 0xf9, 0x46, 0xaf, 0x92, 0xec, 0x0c, 0xb6, 0x75, 0x5d,
	0xfa, 0x07, 0xeb, 0xfb, 0x97, 0xaf, 0x0a, 0x89, 0x1a, 0x83, 0xcf, 0x22, 0xfe, 0xe3, 0xfa, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x26, 0xe1, 0x30, 0xc6, 0x24, 0x01, 0x00, 0x00,
}
