// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smsg/gt_msg.proto

/*
Package smsg is a generated protocol buffer package.

It is generated from these files:
	smsg/gt_msg.proto

It has these top-level messages:
	GtLsReqAuth
	GtLsRespAuth
	GtGsReqLogin
	GtGsRespLogin
	GtGsReqLogout
	GtGsRespLogout
*/
package smsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gamedef "github.com/wenxiu2199/gameserver/src/server/gameproto/gamedef"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GtLsReqAuth struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *GtLsReqAuth) Reset()                    { *m = GtLsReqAuth{} }
func (m *GtLsReqAuth) String() string            { return proto.CompactTextString(m) }
func (*GtLsReqAuth) ProtoMessage()               {}
func (*GtLsReqAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GtLsReqAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GtLsReqAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GtLsRespAuth struct {
	ErrCode    uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg     string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	UserID     uint64 `protobuf:"varint,4,opt,name=userID" json:"userID,omitempty"`
	Sign       string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	UnlockTime int64  `protobuf:"varint,6,opt,name=unlockTime" json:"unlockTime,omitempty"`
}

func (m *GtLsRespAuth) Reset()                    { *m = GtLsRespAuth{} }
func (m *GtLsRespAuth) String() string            { return proto.CompactTextString(m) }
func (*GtLsRespAuth) ProtoMessage()               {}
func (*GtLsRespAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GtLsRespAuth) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GtLsRespAuth) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GtLsRespAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GtLsRespAuth) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GtLsRespAuth) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *GtLsRespAuth) GetUnlockTime() int64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

type GtGsReqLogin struct {
	SeqID   int64                     `protobuf:"varint,1,opt,name=seqID" json:"seqID,omitempty"`
	UserID  uint64                    `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	Account string                    `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	Extra   *gamedef.ExtraAccountInfo `protobuf:"bytes,4,opt,name=extra" json:"extra,omitempty"`
}

func (m *GtGsReqLogin) Reset()                    { *m = GtGsReqLogin{} }
func (m *GtGsReqLogin) String() string            { return proto.CompactTextString(m) }
func (*GtGsReqLogin) ProtoMessage()               {}
func (*GtGsReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GtGsReqLogin) GetSeqID() int64 {
	if m != nil {
		return m.SeqID
	}
	return 0
}

func (m *GtGsReqLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GtGsReqLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GtGsReqLogin) GetExtra() *gamedef.ExtraAccountInfo {
	if m != nil {
		return m.Extra
	}
	return nil
}

type GtGsRespLogin struct {
	ErrCode  uint32             `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg   string             `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	SeqID    int64              `protobuf:"varint,3,opt,name=seqID" json:"seqID,omitempty"`
	UserID   uint64             `protobuf:"varint,4,opt,name=userID" json:"userID,omitempty"`
	Account  string             `protobuf:"bytes,5,opt,name=account" json:"account,omitempty"`
	User     *gamedef.User      `protobuf:"bytes,6,opt,name=user" json:"user,omitempty"`
	Generals []*gamedef.General `protobuf:"bytes,7,rep,name=generals" json:"generals,omitempty"`
}

func (m *GtGsRespLogin) Reset()                    { *m = GtGsRespLogin{} }
func (m *GtGsRespLogin) String() string            { return proto.CompactTextString(m) }
func (*GtGsRespLogin) ProtoMessage()               {}
func (*GtGsRespLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GtGsRespLogin) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GtGsRespLogin) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GtGsRespLogin) GetSeqID() int64 {
	if m != nil {
		return m.SeqID
	}
	return 0
}

func (m *GtGsRespLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GtGsRespLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GtGsRespLogin) GetUser() *gamedef.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GtGsRespLogin) GetGenerals() []*gamedef.General {
	if m != nil {
		return m.Generals
	}
	return nil
}

type GtGsReqLogout struct {
	IsClose bool `protobuf:"varint,1,opt,name=isClose" json:"isClose,omitempty"`
}

func (m *GtGsReqLogout) Reset()                    { *m = GtGsReqLogout{} }
func (m *GtGsReqLogout) String() string            { return proto.CompactTextString(m) }
func (*GtGsReqLogout) ProtoMessage()               {}
func (*GtGsReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GtGsReqLogout) GetIsClose() bool {
	if m != nil {
		return m.IsClose
	}
	return false
}

type GtGsRespLogout struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	UserID  uint64 `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	IsClose bool   `protobuf:"varint,4,opt,name=isClose" json:"isClose,omitempty"`
}

func (m *GtGsRespLogout) Reset()                    { *m = GtGsRespLogout{} }
func (m *GtGsRespLogout) String() string            { return proto.CompactTextString(m) }
func (*GtGsRespLogout) ProtoMessage()               {}
func (*GtGsRespLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GtGsRespLogout) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *GtGsRespLogout) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GtGsRespLogout) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GtGsRespLogout) GetIsClose() bool {
	if m != nil {
		return m.IsClose
	}
	return false
}

func init() {
	proto.RegisterType((*GtLsReqAuth)(nil), "smsg.GtLsReqAuth")
	proto.RegisterType((*GtLsRespAuth)(nil), "smsg.GtLsRespAuth")
	proto.RegisterType((*GtGsReqLogin)(nil), "smsg.GtGsReqLogin")
	proto.RegisterType((*GtGsRespLogin)(nil), "smsg.GtGsRespLogin")
	proto.RegisterType((*GtGsReqLogout)(nil), "smsg.GtGsReqLogout")
	proto.RegisterType((*GtGsRespLogout)(nil), "smsg.GtGsRespLogout")
}

func init() { proto.RegisterFile("smsg/gt_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x6b, 0x27, 0x0d, 0x13, 0x82, 0x60, 0x85, 0x2a, 0xd3, 0x03, 0x0a, 0x3e, 0x19, 0x09,
	0xd9, 0xc2, 0x9c, 0x7a, 0xac, 0x52, 0x14, 0x45, 0x0a, 0x97, 0x15, 0x9c, 0x2b, 0xd7, 0x9e, 0x6c,
	0x2d, 0x62, 0xaf, 0xbb, 0xb3, 0xa6, 0xfd, 0x03, 0xfe, 0x84, 0x8f, 0xe2, 0x6b, 0x90, 0x77, 0x6d,
	0x63, 0x23, 0x7a, 0xe8, 0xc9, 0xf3, 0x66, 0x9e, 0xe7, 0xbd, 0x79, 0x5a, 0x78, 0x45, 0x25, 0x89,
	0x58, 0xe8, 0xeb, 0x92, 0x44, 0x54, 0x2b, 0xa9, 0x25, 0xf3, 0xda, 0xd6, 0xf9, 0x5e, 0x14, 0xfa,
	0xb6, 0xb9, 0x89, 0x32, 0x59, 0xc6, 0xf7, 0x58, 0x3d, 0x14, 0x4d, 0xf2, 0xf1, 0xe2, 0x22, 0x16,
	0x69, 0x89, 0x84, 0xea, 0x07, 0xaa, 0x98, 0x54, 0x16, 0x77, 0x65, 0xdb, 0x35, 0x3f, 0x9b, 0x2a,
	0xc7, 0x83, 0xf9, 0x5e, 0xe7, 0x78, 0xb0, 0x3b, 0x83, 0x0d, 0x2c, 0xb7, 0x7a, 0x4f, 0x1c, 0xef,
	0x2e, 0x1b, 0x7d, 0xcb, 0x7c, 0x38, 0x4d, 0xb3, 0x4c, 0x36, 0x95, 0xf6, 0x9d, 0xb5, 0x13, 0x3e,
	0xe3, 0x3d, 0x64, 0xe7, 0xb0, 0xa8, 0x53, 0xa2, 0x7b, 0xa9, 0x72, 0xff, 0xc4, 0x8c, 0x06, 0x1c,
	0xfc, 0x72, 0xe0, 0xb9, 0xdd, 0x42, 0x75, 0xbf, 0x06, 0x95, 0xda, 0xc8, 0x1c, 0xcd, 0x9a, 0x15,
	0xef, 0x21, 0x3b, 0x83, 0x39, 0x2a, 0xf5, 0x85, 0x44, 0xb7, 0xa4, 0x43, 0x63, 0x61, 0x77, 0x2a,
	0x7c, 0x06, 0xf3, 0x86, 0x50, 0xed, 0xae, 0x7c, 0x6f, 0xed, 0x84, 0x1e, 0xef, 0x10, 0x63, 0xe0,
	0x51, 0x21, 0x2a, 0x7f, 0x66, 0xe8, 0xa6, 0x66, 0x6f, 0x01, 0x9a, 0xea, 0x28, 0xb3, 0xef, 0x5f,
	0x8b, 0x12, 0xfd, 0xf9, 0xda, 0x09, 0x5d, 0x3e, 0xea, 0x04, 0x3f, 0x8d, 0xd1, 0x6d, 0x7b, 0xee,
	0x5e, 0x8a, 0xa2, 0x62, 0xaf, 0x61, 0x46, 0x78, 0xb7, 0xbb, 0x32, 0x36, 0x5d, 0x6e, 0xc1, 0x48,
	0xf2, 0x64, 0x22, 0xf9, 0xb8, 0xc9, 0x18, 0x66, 0xf8, 0xa0, 0x55, 0x6a, 0x3c, 0x2e, 0x93, 0x37,
	0x51, 0x17, 0x77, 0xf4, 0xb9, 0xed, 0x5e, 0x5a, 0xd6, 0xae, 0x3a, 0x48, 0x6e, 0x79, 0xc1, 0x6f,
	0x07, 0x56, 0xd6, 0x09, 0xd5, 0xd6, 0xca, 0xd3, 0x33, 0x1b, 0xcc, 0xbb, 0xff, 0x37, 0xef, 0x3d,
	0x66, 0x7e, 0x36, 0x35, 0xff, 0x0e, 0xbc, 0x96, 0x63, 0xf2, 0x5a, 0x26, 0xab, 0xc1, 0xfb, 0x37,
	0x42, 0xc5, 0xcd, 0x88, 0x7d, 0x80, 0x85, 0xc0, 0x0a, 0x55, 0x7a, 0x24, 0xff, 0x74, 0xed, 0x86,
	0xcb, 0xe4, 0xe5, 0x40, 0xdb, 0xda, 0x01, 0x1f, 0x18, 0xc1, 0xfb, 0xfe, 0xb6, 0x36, 0x65, 0xd9,
	0xe8, 0x56, 0xbb, 0xa0, 0xcd, 0x51, 0x92, 0xbd, 0x6d, 0xc1, 0x7b, 0x18, 0x68, 0x78, 0x31, 0x8a,
	0xa1, 0xe3, 0x3e, 0x31, 0x87, 0xbf, 0x17, 0xbb, 0xff, 0x5e, 0xdc, 0xab, 0x7a, 0x13, 0xd5, 0x9b,
	0xb9, 0x79, 0xfc, 0x9f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x76, 0xda, 0xff, 0x1c, 0x65, 0x03,
	0x00, 0x00,
}
