// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmsg/client_msg.proto

/*
Package cmsg is a generated protocol buffer package.

It is generated from these files:
	cmsg/client_msg.proto

It has these top-level messages:
	CReqSyncSystemTime
	CRespSyncSystemTime
	CReqAuth
	CRespAuth
	CReqLogin
	CRespLogin
	CReqLogout
	CRespLogout
	CNotifyLogout
	CReqUserLoginState
	CRespUserLoginState
	CReqNotifyUserData
	CRespNotifyUserData
*/
package cmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gamedef "gamedef"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 同步系统时间
type CReqSyncSystemTime struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *CReqSyncSystemTime) Reset()                    { *m = CReqSyncSystemTime{} }
func (m *CReqSyncSystemTime) String() string            { return proto.CompactTextString(m) }
func (*CReqSyncSystemTime) ProtoMessage()               {}
func (*CReqSyncSystemTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CReqSyncSystemTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CRespSyncSystemTime struct {
	Timestamp       int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ServerTimestamp int64 `protobuf:"varint,2,opt,name=serverTimestamp" json:"serverTimestamp,omitempty"`
}

func (m *CRespSyncSystemTime) Reset()                    { *m = CRespSyncSystemTime{} }
func (m *CRespSyncSystemTime) String() string            { return proto.CompactTextString(m) }
func (*CRespSyncSystemTime) ProtoMessage()               {}
func (*CRespSyncSystemTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CRespSyncSystemTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CRespSyncSystemTime) GetServerTimestamp() int64 {
	if m != nil {
		return m.ServerTimestamp
	}
	return 0
}

// 玩家认证请求
type CReqAuth struct {
	Account  string                    `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string                    `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Extra    *gamedef.ExtraAccountInfo `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
}

func (m *CReqAuth) Reset()                    { *m = CReqAuth{} }
func (m *CReqAuth) String() string            { return proto.CompactTextString(m) }
func (*CReqAuth) ProtoMessage()               {}
func (*CReqAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CReqAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CReqAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CReqAuth) GetExtra() *gamedef.ExtraAccountInfo {
	if m != nil {
		return m.Extra
	}
	return nil
}

type CRespAuth struct {
	ErrCode    uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg     string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	UserID     uint64 `protobuf:"varint,4,opt,name=userID" json:"userID,omitempty"`
	Sign       string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	UnlockTime int64  `protobuf:"varint,6,opt,name=unlockTime" json:"unlockTime,omitempty"`
}

func (m *CRespAuth) Reset()                    { *m = CRespAuth{} }
func (m *CRespAuth) String() string            { return proto.CompactTextString(m) }
func (*CRespAuth) ProtoMessage()               {}
func (*CRespAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CRespAuth) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespAuth) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CRespAuth) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespAuth) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *CRespAuth) GetUnlockTime() int64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

// 玩家登录请求
type CReqLogin struct {
	UserID uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Sign   string `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
}

func (m *CReqLogin) Reset()                    { *m = CReqLogin{} }
func (m *CReqLogin) String() string            { return proto.CompactTextString(m) }
func (*CReqLogin) ProtoMessage()               {}
func (*CReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CReqLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CReqLogin) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type CRespLogin struct {
	ErrCode     uint32        `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg      string        `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	UserID      uint64        `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	User        *gamedef.User `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	IsReconnect bool          `protobuf:"varint,5,opt,name=isReconnect" json:"isReconnect,omitempty"`
}

func (m *CRespLogin) Reset()                    { *m = CRespLogin{} }
func (m *CRespLogin) String() string            { return proto.CompactTextString(m) }
func (*CRespLogin) ProtoMessage()               {}
func (*CRespLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CRespLogin) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespLogin) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespLogin) GetUser() *gamedef.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CRespLogin) GetIsReconnect() bool {
	if m != nil {
		return m.IsReconnect
	}
	return false
}

// 玩家登出请求
type CReqLogout struct {
}

func (m *CReqLogout) Reset()                    { *m = CReqLogout{} }
func (m *CReqLogout) String() string            { return proto.CompactTextString(m) }
func (*CReqLogout) ProtoMessage()               {}
func (*CReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type CRespLogout struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CRespLogout) Reset()                    { *m = CRespLogout{} }
func (m *CRespLogout) String() string            { return proto.CompactTextString(m) }
func (*CRespLogout) ProtoMessage()               {}
func (*CRespLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CRespLogout) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespLogout) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 玩家被提出
type CNotifyLogout struct {
	LoginInfo *gamedef.LoginInfo `protobuf:"bytes,1,opt,name=loginInfo" json:"loginInfo,omitempty"`
}

func (m *CNotifyLogout) Reset()                    { *m = CNotifyLogout{} }
func (m *CNotifyLogout) String() string            { return proto.CompactTextString(m) }
func (*CNotifyLogout) ProtoMessage()               {}
func (*CNotifyLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CNotifyLogout) GetLoginInfo() *gamedef.LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

// 玩家登录状态请求
type CReqUserLoginState struct {
	UserID uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Sign   string `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
}

func (m *CReqUserLoginState) Reset()                    { *m = CReqUserLoginState{} }
func (m *CReqUserLoginState) String() string            { return proto.CompactTextString(m) }
func (*CReqUserLoginState) ProtoMessage()               {}
func (*CReqUserLoginState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CReqUserLoginState) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CReqUserLoginState) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type CRespUserLoginState struct {
	ErrCode   uint32             `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg    string             `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	UserID    uint64             `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	IsLogin   bool               `protobuf:"varint,4,opt,name=isLogin" json:"isLogin,omitempty"`
	LoginInfo *gamedef.LoginInfo `protobuf:"bytes,5,opt,name=loginInfo" json:"loginInfo,omitempty"`
}

func (m *CRespUserLoginState) Reset()                    { *m = CRespUserLoginState{} }
func (m *CRespUserLoginState) String() string            { return proto.CompactTextString(m) }
func (*CRespUserLoginState) ProtoMessage()               {}
func (*CRespUserLoginState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CRespUserLoginState) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespUserLoginState) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespUserLoginState) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespUserLoginState) GetIsLogin() bool {
	if m != nil {
		return m.IsLogin
	}
	return false
}

func (m *CRespUserLoginState) GetLoginInfo() *gamedef.LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

// 请求玩家数据
type CReqNotifyUserData struct {
}

func (m *CReqNotifyUserData) Reset()                    { *m = CReqNotifyUserData{} }
func (m *CReqNotifyUserData) String() string            { return proto.CompactTextString(m) }
func (*CReqNotifyUserData) ProtoMessage()               {}
func (*CReqNotifyUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// 返回玩家数据
type CRespNotifyUserData struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CRespNotifyUserData) Reset()                    { *m = CRespNotifyUserData{} }
func (m *CRespNotifyUserData) String() string            { return proto.CompactTextString(m) }
func (*CRespNotifyUserData) ProtoMessage()               {}
func (*CRespNotifyUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CRespNotifyUserData) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespNotifyUserData) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*CReqSyncSystemTime)(nil), "cmsg.CReqSyncSystemTime")
	proto.RegisterType((*CRespSyncSystemTime)(nil), "cmsg.CRespSyncSystemTime")
	proto.RegisterType((*CReqAuth)(nil), "cmsg.CReqAuth")
	proto.RegisterType((*CRespAuth)(nil), "cmsg.CRespAuth")
	proto.RegisterType((*CReqLogin)(nil), "cmsg.CReqLogin")
	proto.RegisterType((*CRespLogin)(nil), "cmsg.CRespLogin")
	proto.RegisterType((*CReqLogout)(nil), "cmsg.CReqLogout")
	proto.RegisterType((*CRespLogout)(nil), "cmsg.CRespLogout")
	proto.RegisterType((*CNotifyLogout)(nil), "cmsg.CNotifyLogout")
	proto.RegisterType((*CReqUserLoginState)(nil), "cmsg.CReqUserLoginState")
	proto.RegisterType((*CRespUserLoginState)(nil), "cmsg.CRespUserLoginState")
	proto.RegisterType((*CReqNotifyUserData)(nil), "cmsg.CReqNotifyUserData")
	proto.RegisterType((*CRespNotifyUserData)(nil), "cmsg.CRespNotifyUserData")
}

func init() { proto.RegisterFile("cmsg/client_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0xd3, 0xa5, 0xb0, 0xf4, 0x55, 0x62, 0x32, 0x2a, 0xa9, 0x1b, 0x63, 0x70, 0x4e, 0x9c,
	0xc0, 0xe0, 0xc1, 0xa3, 0x12, 0xd6, 0x98, 0x4d, 0x56, 0x0f, 0xc3, 0x7a, 0x34, 0x9b, 0x5a, 0x1e,
	0xb5, 0x91, 0xce, 0xc0, 0xcc, 0x54, 0xe5, 0x6f, 0xf1, 0xe8, 0xd1, 0x7f, 0xd2, 0xcc, 0x6b, 0x0b,
	0x74, 0xe3, 0xc1, 0x26, 0x7b, 0x62, 0xde, 0x8f, 0xf9, 0xbe, 0xef, 0xe7, 0x91, 0x29, 0x3c, 0x49,
	0x72, 0x93, 0x4e, 0x93, 0x4d, 0x86, 0xd2, 0xde, 0xe6, 0x26, 0x9d, 0x6c, 0xb5, 0xb2, 0x8a, 0xf9,
	0x2e, 0x7d, 0x31, 0x4c, 0xe3, 0x1c, 0x57, 0xb8, 0x9e, 0xba, 0xdf, 0xdb, 0x15, 0xae, 0xcb, 0x2a,
	0x9f, 0x01, 0x5b, 0x08, 0xdc, 0x2d, 0xf7, 0x32, 0x59, 0xee, 0x8d, 0xc5, 0xfc, 0x26, 0xcb, 0x91,
	0x3d, 0x83, 0xc0, 0x66, 0x39, 0x1a, 0x1b, 0xe7, 0xdb, 0xc8, 0x1b, 0x79, 0xe3, 0x8e, 0x38, 0x26,
	0xf8, 0x67, 0x78, 0xb4, 0x10, 0x68, 0xb6, 0x6d, 0x2e, 0xb1, 0x31, 0x3c, 0x34, 0xa8, 0xbf, 0xa3,
	0xbe, 0x39, 0xf4, 0x9c, 0x51, 0xcf, 0xdd, 0x34, 0xdf, 0x41, 0xdf, 0x59, 0x9a, 0x17, 0xf6, 0x2b,
	0x8b, 0xe0, 0x3c, 0x4e, 0x12, 0x55, 0x48, 0x4b, 0x8a, 0x81, 0xa8, 0x43, 0x76, 0x01, 0xfd, 0x6d,
	0x6c, 0xcc, 0x0f, 0xa5, 0x57, 0x24, 0x14, 0x88, 0x43, 0xcc, 0xa6, 0xd0, 0xc5, 0x9f, 0x56, 0xc7,
	0x51, 0x67, 0xe4, 0x8d, 0xc3, 0xd9, 0xd3, 0x49, 0x05, 0x3f, 0x79, 0xe7, 0xb2, 0xf3, 0x52, 0xe1,
	0x4a, 0xae, 0x95, 0x28, 0xfb, 0xf8, 0x6f, 0x0f, 0x02, 0x42, 0xaa, 0x87, 0xa2, 0xd6, 0x0b, 0xb5,
	0x42, 0x1a, 0x3a, 0x10, 0x75, 0xc8, 0x86, 0xd0, 0x43, 0xad, 0x3f, 0x98, 0xb4, 0x1a, 0x59, 0x45,
	0xa7, 0x36, 0x3b, 0x4d, 0x9b, 0x43, 0xe8, 0x15, 0x06, 0xf5, 0xd5, 0x65, 0xe4, 0x8f, 0xbc, 0xb1,
	0x2f, 0xaa, 0x88, 0x31, 0xf0, 0x4d, 0x96, 0xca, 0xa8, 0x4b, 0xed, 0x74, 0x66, 0xcf, 0x01, 0x0a,
	0xb9, 0x51, 0xc9, 0x37, 0xb7, 0x8b, 0xa8, 0x47, 0xdb, 0x39, 0xc9, 0xf0, 0xd7, 0x64, 0x72, 0x77,
	0xad, 0xd2, 0x4c, 0x9e, 0x08, 0x7b, 0xff, 0x14, 0x3e, 0x3b, 0x0a, 0xf3, 0x5f, 0x1e, 0x00, 0xe1,
	0x95, 0x57, 0xdb, 0xf3, 0x1d, 0x87, 0x75, 0x1a, 0xc3, 0x5e, 0x80, 0xef, 0x4e, 0xc4, 0x16, 0xce,
	0x06, 0x87, 0x3d, 0x7f, 0x32, 0xa8, 0x05, 0x95, 0xd8, 0x08, 0xc2, 0xcc, 0x08, 0x4c, 0x94, 0x94,
	0x98, 0x58, 0xe2, 0xed, 0x8b, 0xd3, 0x14, 0x7f, 0x40, 0xe6, 0x1c, 0x96, 0x2a, 0x2c, 0x7f, 0x03,
	0x61, 0x6d, 0x55, 0x15, 0xb6, 0xbd, 0x57, 0x3e, 0x87, 0xc1, 0xe2, 0xa3, 0xb2, 0xd9, 0x7a, 0x5f,
	0x49, 0xbc, 0x84, 0x60, 0xe3, 0xb8, 0xdd, 0x1f, 0x4e, 0x22, 0xe1, 0x8c, 0x1d, 0x9c, 0x5e, 0xd7,
	0x15, 0x71, 0x6c, 0xe2, 0x6f, 0xcb, 0x47, 0xe1, 0x28, 0xa8, 0xbe, 0xb4, 0xb1, 0xc5, 0x56, 0x1b,
	0xff, 0xe3, 0x55, 0x6f, 0xe4, 0x8e, 0xc6, 0xfd, 0xad, 0x3e, 0x82, 0xf3, 0xcc, 0x90, 0x32, 0x6d,
	0xbf, 0x2f, 0xea, 0xb0, 0xc9, 0xdb, 0xfd, 0x1f, 0xde, 0xc7, 0x25, 0x6f, 0xb9, 0x35, 0xe7, 0xf8,
	0x32, 0xb6, 0x31, 0x7f, 0x5f, 0x21, 0x34, 0xd3, 0xed, 0x11, 0xbe, 0xf4, 0xe8, 0x53, 0xf3, 0xea,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x50, 0x31, 0x0a, 0xa1, 0x04, 0x00, 0x00,
}
