// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmsg/client_msg.proto

/*
Package cmsg is a generated protocol buffer package.

It is generated from these files:
	cmsg/client_msg.proto

It has these top-level messages:
	CReqSyncSystemTime
	CRespSyncSystemTime
	CReqAuth
	CRespAuth
	CNotifyLoginInfo
	CReqLogin
	CRespLogin
	CReqLogout
	CRespLogout
	CNotifyLogout
	CReqNotifyUserData
	CRespNotifyUserData
	CReqUseSkill
	CRespUseSkill
	CNotifyUseSkill
	CNotifyGameStart
	CNotifyGeneralStatus
*/
package cmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gamedef "github.com/wenxiu2199/gameserver/src/server/gameproto/gamedef"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 同步系统时间
type CReqSyncSystemTime struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *CReqSyncSystemTime) Reset()                    { *m = CReqSyncSystemTime{} }
func (m *CReqSyncSystemTime) String() string            { return proto.CompactTextString(m) }
func (*CReqSyncSystemTime) ProtoMessage()               {}
func (*CReqSyncSystemTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CReqSyncSystemTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CRespSyncSystemTime struct {
	Timestamp       int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ServerTimestamp int64 `protobuf:"varint,2,opt,name=serverTimestamp" json:"serverTimestamp,omitempty"`
}

func (m *CRespSyncSystemTime) Reset()                    { *m = CRespSyncSystemTime{} }
func (m *CRespSyncSystemTime) String() string            { return proto.CompactTextString(m) }
func (*CRespSyncSystemTime) ProtoMessage()               {}
func (*CRespSyncSystemTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CRespSyncSystemTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CRespSyncSystemTime) GetServerTimestamp() int64 {
	if m != nil {
		return m.ServerTimestamp
	}
	return 0
}

// 玩家认证请求
type CReqAuth struct {
	Account  string                    `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string                    `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Extra    *gamedef.ExtraAccountInfo `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
}

func (m *CReqAuth) Reset()                    { *m = CReqAuth{} }
func (m *CReqAuth) String() string            { return proto.CompactTextString(m) }
func (*CReqAuth) ProtoMessage()               {}
func (*CReqAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CReqAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CReqAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CReqAuth) GetExtra() *gamedef.ExtraAccountInfo {
	if m != nil {
		return m.Extra
	}
	return nil
}

type CRespAuth struct {
	ErrCode    uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg     string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	UserID     uint64 `protobuf:"varint,4,opt,name=userID" json:"userID,omitempty"`
	Sign       string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	UnlockTime int64  `protobuf:"varint,6,opt,name=unlockTime" json:"unlockTime,omitempty"`
}

func (m *CRespAuth) Reset()                    { *m = CRespAuth{} }
func (m *CRespAuth) String() string            { return proto.CompactTextString(m) }
func (*CRespAuth) ProtoMessage()               {}
func (*CRespAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CRespAuth) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespAuth) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CRespAuth) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespAuth) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *CRespAuth) GetUnlockTime() int64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

// 账号登录通知
type CNotifyLoginInfo struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Ip      string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *CNotifyLoginInfo) Reset()                    { *m = CNotifyLoginInfo{} }
func (m *CNotifyLoginInfo) String() string            { return proto.CompactTextString(m) }
func (*CNotifyLoginInfo) ProtoMessage()               {}
func (*CNotifyLoginInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CNotifyLoginInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CNotifyLoginInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// 玩家登录请求
type CReqLogin struct {
	UserID uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Sign   string `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
}

func (m *CReqLogin) Reset()                    { *m = CReqLogin{} }
func (m *CReqLogin) String() string            { return proto.CompactTextString(m) }
func (*CReqLogin) ProtoMessage()               {}
func (*CReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CReqLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CReqLogin) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type CRespLogin struct {
	ErrCode     uint32        `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg      string        `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	UserID      uint64        `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	User        *gamedef.User `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	IsReconnect bool          `protobuf:"varint,5,opt,name=isReconnect" json:"isReconnect,omitempty"`
}

func (m *CRespLogin) Reset()                    { *m = CRespLogin{} }
func (m *CRespLogin) String() string            { return proto.CompactTextString(m) }
func (*CRespLogin) ProtoMessage()               {}
func (*CRespLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CRespLogin) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespLogin) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespLogin) GetUser() *gamedef.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CRespLogin) GetIsReconnect() bool {
	if m != nil {
		return m.IsReconnect
	}
	return false
}

// 玩家登出请求
type CReqLogout struct {
}

func (m *CReqLogout) Reset()                    { *m = CReqLogout{} }
func (m *CReqLogout) String() string            { return proto.CompactTextString(m) }
func (*CReqLogout) ProtoMessage()               {}
func (*CReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type CRespLogout struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CRespLogout) Reset()                    { *m = CRespLogout{} }
func (m *CRespLogout) String() string            { return proto.CompactTextString(m) }
func (*CRespLogout) ProtoMessage()               {}
func (*CRespLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CRespLogout) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespLogout) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 玩家被提出
type CNotifyLogout struct {
	LoginInfo *gamedef.LoginInfo `protobuf:"bytes,1,opt,name=loginInfo" json:"loginInfo,omitempty"`
}

func (m *CNotifyLogout) Reset()                    { *m = CNotifyLogout{} }
func (m *CNotifyLogout) String() string            { return proto.CompactTextString(m) }
func (*CNotifyLogout) ProtoMessage()               {}
func (*CNotifyLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CNotifyLogout) GetLoginInfo() *gamedef.LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

// 请求玩家数据
type CReqNotifyUserData struct {
}

func (m *CReqNotifyUserData) Reset()                    { *m = CReqNotifyUserData{} }
func (m *CReqNotifyUserData) String() string            { return proto.CompactTextString(m) }
func (*CReqNotifyUserData) ProtoMessage()               {}
func (*CReqNotifyUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// 返回玩家数据
type CRespNotifyUserData struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CRespNotifyUserData) Reset()                    { *m = CRespNotifyUserData{} }
func (m *CRespNotifyUserData) String() string            { return proto.CompactTextString(m) }
func (*CRespNotifyUserData) ProtoMessage()               {}
func (*CRespNotifyUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CRespNotifyUserData) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespNotifyUserData) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ===============Game数据====================
type CReqUseSkill struct {
	SkillID uint32 `protobuf:"varint,1,opt,name=skillID" json:"skillID,omitempty"`
}

func (m *CReqUseSkill) Reset()                    { *m = CReqUseSkill{} }
func (m *CReqUseSkill) String() string            { return proto.CompactTextString(m) }
func (*CReqUseSkill) ProtoMessage()               {}
func (*CReqUseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CReqUseSkill) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

// 返回玩家数据
type CRespUseSkill struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	SkillID uint32 `protobuf:"varint,3,opt,name=skillID" json:"skillID,omitempty"`
}

func (m *CRespUseSkill) Reset()                    { *m = CRespUseSkill{} }
func (m *CRespUseSkill) String() string            { return proto.CompactTextString(m) }
func (*CRespUseSkill) ProtoMessage()               {}
func (*CRespUseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CRespUseSkill) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespUseSkill) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespUseSkill) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

type CNotifyUseSkill struct {
	UserID  uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	SkillID uint32 `protobuf:"varint,2,opt,name=skillID" json:"skillID,omitempty"`
}

func (m *CNotifyUseSkill) Reset()                    { *m = CNotifyUseSkill{} }
func (m *CNotifyUseSkill) String() string            { return proto.CompactTextString(m) }
func (*CNotifyUseSkill) ProtoMessage()               {}
func (*CNotifyUseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CNotifyUseSkill) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CNotifyUseSkill) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

type CNotifyGameStart struct {
	Generals []*gamedef.GameGeneral `protobuf:"bytes,1,rep,name=generals" json:"generals,omitempty"`
}

func (m *CNotifyGameStart) Reset()                    { *m = CNotifyGameStart{} }
func (m *CNotifyGameStart) String() string            { return proto.CompactTextString(m) }
func (*CNotifyGameStart) ProtoMessage()               {}
func (*CNotifyGameStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CNotifyGameStart) GetGenerals() []*gamedef.GameGeneral {
	if m != nil {
		return m.Generals
	}
	return nil
}

type CNotifyGeneralStatus struct {
	GameGeneral *gamedef.GameGeneral `protobuf:"bytes,1,opt,name=gameGeneral" json:"gameGeneral,omitempty"`
}

func (m *CNotifyGeneralStatus) Reset()                    { *m = CNotifyGeneralStatus{} }
func (m *CNotifyGeneralStatus) String() string            { return proto.CompactTextString(m) }
func (*CNotifyGeneralStatus) ProtoMessage()               {}
func (*CNotifyGeneralStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CNotifyGeneralStatus) GetGameGeneral() *gamedef.GameGeneral {
	if m != nil {
		return m.GameGeneral
	}
	return nil
}

func init() {
	proto.RegisterType((*CReqSyncSystemTime)(nil), "cmsg.CReqSyncSystemTime")
	proto.RegisterType((*CRespSyncSystemTime)(nil), "cmsg.CRespSyncSystemTime")
	proto.RegisterType((*CReqAuth)(nil), "cmsg.CReqAuth")
	proto.RegisterType((*CRespAuth)(nil), "cmsg.CRespAuth")
	proto.RegisterType((*CNotifyLoginInfo)(nil), "cmsg.CNotifyLoginInfo")
	proto.RegisterType((*CReqLogin)(nil), "cmsg.CReqLogin")
	proto.RegisterType((*CRespLogin)(nil), "cmsg.CRespLogin")
	proto.RegisterType((*CReqLogout)(nil), "cmsg.CReqLogout")
	proto.RegisterType((*CRespLogout)(nil), "cmsg.CRespLogout")
	proto.RegisterType((*CNotifyLogout)(nil), "cmsg.CNotifyLogout")
	proto.RegisterType((*CReqNotifyUserData)(nil), "cmsg.CReqNotifyUserData")
	proto.RegisterType((*CRespNotifyUserData)(nil), "cmsg.CRespNotifyUserData")
	proto.RegisterType((*CReqUseSkill)(nil), "cmsg.CReqUseSkill")
	proto.RegisterType((*CRespUseSkill)(nil), "cmsg.CRespUseSkill")
	proto.RegisterType((*CNotifyUseSkill)(nil), "cmsg.CNotifyUseSkill")
	proto.RegisterType((*CNotifyGameStart)(nil), "cmsg.CNotifyGameStart")
	proto.RegisterType((*CNotifyGeneralStatus)(nil), "cmsg.CNotifyGeneralStatus")
}

func init() { proto.RegisterFile("cmsg/client_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0xe6, 0x92, 0x34, 0x26, 0x73, 0x8d, 0x95, 0xb5, 0x96, 0xb3, 0x88, 0xc4, 0x7d, 0xca, 0x53,
	0xa2, 0x11, 0x94, 0x82, 0x20, 0xe5, 0x2a, 0xa5, 0x50, 0xfb, 0xb0, 0x69, 0x9f, 0x44, 0xca, 0xf5,
	0x32, 0xb9, 0x2e, 0xbd, 0xbb, 0xbd, 0xee, 0xee, 0xd9, 0xf6, 0x6f, 0xf1, 0xd1, 0x7f, 0x54, 0x76,
	0xef, 0x67, 0xa4, 0x0a, 0xf1, 0x29, 0x33, 0x73, 0xdf, 0x7c, 0xf3, 0xcd, 0xb7, 0xbb, 0x81, 0x17,
	0x61, 0xa2, 0xa2, 0x59, 0x18, 0x73, 0x4c, 0xf5, 0x65, 0xa2, 0xa2, 0x69, 0x26, 0x85, 0x16, 0xa4,
	0x67, 0xca, 0xfb, 0xa7, 0x11, 0xd7, 0xd7, 0xf9, 0xd5, 0x34, 0x14, 0xc9, 0xec, 0x0e, 0xd3, 0x7b,
	0x9e, 0xcf, 0xdf, 0x1d, 0x1c, 0xcc, 0xa2, 0x20, 0x41, 0x85, 0xf2, 0x07, 0xca, 0x99, 0x92, 0xe1,
	0xac, 0x0c, 0x4d, 0xd5, 0x36, 0xdb, 0x68, 0x89, 0x2b, 0xfb, 0x7b, 0xb9, 0xc4, 0x55, 0xc1, 0x49,
	0xe7, 0x40, 0x7c, 0x86, 0xb7, 0x8b, 0x87, 0x34, 0x5c, 0x3c, 0x28, 0x8d, 0xc9, 0x39, 0x4f, 0x90,
	0xbc, 0x82, 0xa1, 0xe6, 0x09, 0x2a, 0x1d, 0x24, 0x99, 0xe7, 0x8c, 0x9d, 0x49, 0x97, 0x35, 0x05,
	0xfa, 0x1d, 0x9e, 0xfb, 0x0c, 0x55, 0xb6, 0x49, 0x13, 0x99, 0xc0, 0x4e, 0xa1, 0xe9, 0xbc, 0xc6,
	0x74, 0x2c, 0xe6, 0xcf, 0x32, 0xbd, 0x85, 0x81, 0x91, 0x74, 0x98, 0xeb, 0x6b, 0xe2, 0xc1, 0x93,
	0x20, 0x0c, 0x45, 0x9e, 0x6a, 0xcb, 0x38, 0x64, 0x55, 0x4a, 0xf6, 0x61, 0x90, 0x05, 0x4a, 0xdd,
	0x09, 0xb9, 0xb4, 0x44, 0x43, 0x56, 0xe7, 0x64, 0x06, 0x5b, 0x78, 0xaf, 0x65, 0xe0, 0x75, 0xc7,
	0xce, 0xc4, 0x9d, 0xbf, 0x9c, 0x96, 0xcb, 0x4f, 0xbf, 0x98, 0xea, 0x61, 0xc1, 0x70, 0x92, 0xae,
	0x04, 0x2b, 0x70, 0xf4, 0x97, 0x03, 0x43, 0xbb, 0x52, 0x35, 0x14, 0xa5, 0xf4, 0xc5, 0x12, 0xed,
	0xd0, 0x11, 0xab, 0x52, 0xb2, 0x07, 0x7d, 0x94, 0xf2, 0xab, 0x8a, 0xca, 0x91, 0x65, 0xd6, 0x96,
	0xd9, 0x5d, 0x97, 0xb9, 0x07, 0xfd, 0x5c, 0xa1, 0x3c, 0x39, 0xf2, 0x7a, 0x63, 0x67, 0xd2, 0x63,
	0x65, 0x46, 0x08, 0xf4, 0x14, 0x8f, 0x52, 0x6f, 0xcb, 0xc2, 0x6d, 0x4c, 0x5e, 0x03, 0xe4, 0x69,
	0x2c, 0xc2, 0x1b, 0xe3, 0x85, 0xd7, 0xb7, 0xee, 0xb4, 0x2a, 0xf4, 0x13, 0x3c, 0xf3, 0xcf, 0x84,
	0xe6, 0xab, 0x87, 0x53, 0x11, 0xf1, 0xd4, 0x2c, 0xf0, 0x0f, 0x83, 0x9e, 0x42, 0x87, 0x67, 0xa5,
	0xce, 0x0e, 0xcf, 0xe8, 0x47, 0xbb, 0xe2, 0xad, 0x6d, 0x6d, 0xc9, 0x72, 0x1e, 0x95, 0xd5, 0x69,
	0x64, 0xd1, 0x9f, 0x0e, 0x80, 0x35, 0xa7, 0x68, 0xdd, 0xdc, 0x9d, 0x66, 0x58, 0x77, 0x6d, 0xd8,
	0x1b, 0xe8, 0x99, 0xc8, 0x3a, 0xe3, 0xce, 0x47, 0xf5, 0x29, 0x5d, 0x28, 0x94, 0xcc, 0x7e, 0x22,
	0x63, 0x70, 0xb9, 0x62, 0x18, 0x8a, 0x34, 0xc5, 0x50, 0x5b, 0xb7, 0x06, 0xac, 0x5d, 0xa2, 0xdb,
	0x56, 0x9c, 0x59, 0x4b, 0xe4, 0x9a, 0x7e, 0x06, 0xb7, 0x92, 0x2a, 0x72, 0xbd, 0xb9, 0x56, 0x7a,
	0x08, 0xa3, 0xc6, 0x63, 0x43, 0xf1, 0x16, 0x86, 0x71, 0xe5, 0xb6, 0x25, 0x71, 0xe7, 0xa4, 0x56,
	0x5a, 0x9f, 0x03, 0x6b, 0x40, 0x74, 0xb7, 0x78, 0x52, 0x05, 0x8b, 0xd9, 0xe5, 0x28, 0xd0, 0x01,
	0x3d, 0x2e, 0x1f, 0xcd, 0x7a, 0xf9, 0x3f, 0x14, 0x4e, 0x60, 0xdb, 0xd0, 0x5f, 0x28, 0x5c, 0xdc,
	0xf0, 0x38, 0x36, 0x0c, 0xca, 0x04, 0xe5, 0x59, 0x8e, 0x58, 0x95, 0xd2, 0x6f, 0x30, 0xb2, 0x23,
	0xdb, 0xd0, 0xcd, 0x2f, 0x76, 0x45, 0xde, 0x5d, 0x27, 0xf7, 0x61, 0xc7, 0xaf, 0x77, 0x29, 0xe8,
	0xff, 0x76, 0xa9, 0x5a, 0x24, 0x9d, 0x75, 0x92, 0xa3, 0xfa, 0x46, 0x1f, 0x07, 0x09, 0x2e, 0x74,
	0x20, 0x8d, 0xe1, 0x83, 0x08, 0x53, 0x94, 0x41, 0xac, 0x3c, 0x67, 0xdc, 0x9d, 0xb8, 0xf3, 0xdd,
	0xda, 0x6f, 0x83, 0x3a, 0x2e, 0x3e, 0xb2, 0x1a, 0x45, 0xcf, 0x60, 0xb7, 0x62, 0x29, 0x4a, 0x0b,
	0x1d, 0xe8, 0x5c, 0x91, 0x0f, 0xe0, 0x46, 0x4d, 0x43, 0x79, 0x78, 0x8f, 0x93, 0xb5, 0x81, 0x57,
	0x7d, 0xfb, 0xd7, 0xf8, 0xfe, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0x0d, 0x2f, 0xc4, 0x87,
	0x05, 0x00, 0x00,
}
