// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmsg/client_msg.proto

/*
Package cmsg is a generated protocol buffer package.

It is generated from these files:
	cmsg/client_msg.proto

It has these top-level messages:
	CReqSyncSystemTime
	CRespSyncSystemTime
	CReqAuth
	CRespAuth
	CNotifyLoginInfo
	CReqLogin
	CRespLogin
	CReqLogout
	CRespLogout
	CNotifyLogout
	CReqNotifyUserData
	CRespNotifyUserData
	CNotifyDataChange
	CReqUseSkill
	CRespUseSkill
	CNotifyUseSkill
	CNotifyGameStart
	CNotifyGeneralStatus
	CNotifyGameStage
	CNotifyGameResult
	CReqUserInit
	CRespUserInit
	CReqStageFight
	CRespStageFight
*/
package cmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import gamedef "github.com/wenxiu2199/gameserver/src/server/gameproto/gamedef"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CNotifyDataChangeType int32

const (
	CNotifyDataChange_DCTInvalid CNotifyDataChangeType = 0
	CNotifyDataChange_DCTUser    CNotifyDataChangeType = 1
	CNotifyDataChange_DCTGeneral CNotifyDataChangeType = 2
)

var CNotifyDataChangeType_name = map[int32]string{
	0: "DCTInvalid",
	1: "DCTUser",
	2: "DCTGeneral",
}
var CNotifyDataChangeType_value = map[string]int32{
	"DCTInvalid": 0,
	"DCTUser":    1,
	"DCTGeneral": 2,
}

func (x CNotifyDataChangeType) String() string {
	return proto.EnumName(CNotifyDataChangeType_name, int32(x))
}
func (CNotifyDataChangeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

// 同步系统时间
type CReqSyncSystemTime struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *CReqSyncSystemTime) Reset()                    { *m = CReqSyncSystemTime{} }
func (m *CReqSyncSystemTime) String() string            { return proto.CompactTextString(m) }
func (*CReqSyncSystemTime) ProtoMessage()               {}
func (*CReqSyncSystemTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CReqSyncSystemTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CRespSyncSystemTime struct {
	Timestamp       int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ServerTimestamp int64 `protobuf:"varint,2,opt,name=serverTimestamp" json:"serverTimestamp,omitempty"`
}

func (m *CRespSyncSystemTime) Reset()                    { *m = CRespSyncSystemTime{} }
func (m *CRespSyncSystemTime) String() string            { return proto.CompactTextString(m) }
func (*CRespSyncSystemTime) ProtoMessage()               {}
func (*CRespSyncSystemTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CRespSyncSystemTime) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CRespSyncSystemTime) GetServerTimestamp() int64 {
	if m != nil {
		return m.ServerTimestamp
	}
	return 0
}

// 玩家认证请求
type CReqAuth struct {
	Account  string                    `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string                    `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Extra    *gamedef.ExtraAccountInfo `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
}

func (m *CReqAuth) Reset()                    { *m = CReqAuth{} }
func (m *CReqAuth) String() string            { return proto.CompactTextString(m) }
func (*CReqAuth) ProtoMessage()               {}
func (*CReqAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CReqAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CReqAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CReqAuth) GetExtra() *gamedef.ExtraAccountInfo {
	if m != nil {
		return m.Extra
	}
	return nil
}

type CRespAuth struct {
	ErrCode    uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg     string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Account    string `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	UserID     uint64 `protobuf:"varint,4,opt,name=userID" json:"userID,omitempty"`
	Sign       string `protobuf:"bytes,5,opt,name=sign" json:"sign,omitempty"`
	UnlockTime int64  `protobuf:"varint,6,opt,name=unlockTime" json:"unlockTime,omitempty"`
}

func (m *CRespAuth) Reset()                    { *m = CRespAuth{} }
func (m *CRespAuth) String() string            { return proto.CompactTextString(m) }
func (*CRespAuth) ProtoMessage()               {}
func (*CRespAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CRespAuth) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespAuth) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespAuth) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CRespAuth) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespAuth) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *CRespAuth) GetUnlockTime() int64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

// 账号登录通知
type CNotifyLoginInfo struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Ip      string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
}

func (m *CNotifyLoginInfo) Reset()                    { *m = CNotifyLoginInfo{} }
func (m *CNotifyLoginInfo) String() string            { return proto.CompactTextString(m) }
func (*CNotifyLoginInfo) ProtoMessage()               {}
func (*CNotifyLoginInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CNotifyLoginInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CNotifyLoginInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// 玩家登录请求
type CReqLogin struct {
	UserID uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Sign   string `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
}

func (m *CReqLogin) Reset()                    { *m = CReqLogin{} }
func (m *CReqLogin) String() string            { return proto.CompactTextString(m) }
func (*CReqLogin) ProtoMessage()               {}
func (*CReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CReqLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CReqLogin) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type CRespLogin struct {
	ErrCode     uint32        `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg      string        `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	UserID      uint64        `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
	User        *gamedef.User `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	IsReconnect bool          `protobuf:"varint,5,opt,name=isReconnect" json:"isReconnect,omitempty"`
}

func (m *CRespLogin) Reset()                    { *m = CRespLogin{} }
func (m *CRespLogin) String() string            { return proto.CompactTextString(m) }
func (*CRespLogin) ProtoMessage()               {}
func (*CRespLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CRespLogin) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespLogin) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespLogin) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CRespLogin) GetUser() *gamedef.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CRespLogin) GetIsReconnect() bool {
	if m != nil {
		return m.IsReconnect
	}
	return false
}

// 玩家登出请求
type CReqLogout struct {
}

func (m *CReqLogout) Reset()                    { *m = CReqLogout{} }
func (m *CReqLogout) String() string            { return proto.CompactTextString(m) }
func (*CReqLogout) ProtoMessage()               {}
func (*CReqLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type CRespLogout struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CRespLogout) Reset()                    { *m = CRespLogout{} }
func (m *CRespLogout) String() string            { return proto.CompactTextString(m) }
func (*CRespLogout) ProtoMessage()               {}
func (*CRespLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CRespLogout) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespLogout) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 玩家被提出
type CNotifyLogout struct {
	LoginInfo *gamedef.LoginInfo `protobuf:"bytes,1,opt,name=loginInfo" json:"loginInfo,omitempty"`
}

func (m *CNotifyLogout) Reset()                    { *m = CNotifyLogout{} }
func (m *CNotifyLogout) String() string            { return proto.CompactTextString(m) }
func (*CNotifyLogout) ProtoMessage()               {}
func (*CNotifyLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CNotifyLogout) GetLoginInfo() *gamedef.LoginInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

// 请求玩家数据
type CReqNotifyUserData struct {
}

func (m *CReqNotifyUserData) Reset()                    { *m = CReqNotifyUserData{} }
func (m *CReqNotifyUserData) String() string            { return proto.CompactTextString(m) }
func (*CReqNotifyUserData) ProtoMessage()               {}
func (*CReqNotifyUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// 返回玩家数据
type CRespNotifyUserData struct {
	ErrCode  uint32             `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg   string             `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	Generals []*gamedef.General `protobuf:"bytes,3,rep,name=generals" json:"generals,omitempty"`
	Items    []*gamedef.Item    `protobuf:"bytes,4,rep,name=Items" json:"Items,omitempty"`
}

func (m *CRespNotifyUserData) Reset()                    { *m = CRespNotifyUserData{} }
func (m *CRespNotifyUserData) String() string            { return proto.CompactTextString(m) }
func (*CRespNotifyUserData) ProtoMessage()               {}
func (*CRespNotifyUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CRespNotifyUserData) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespNotifyUserData) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespNotifyUserData) GetGenerals() []*gamedef.General {
	if m != nil {
		return m.Generals
	}
	return nil
}

func (m *CRespNotifyUserData) GetItems() []*gamedef.Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type CNotifyDataChange struct {
	Changes  []CNotifyDataChangeType `protobuf:"varint,1,rep,packed,name=changes,enum=cmsg.CNotifyDataChangeType" json:"changes,omitempty"`
	User     *gamedef.User           `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Generals []*gamedef.General      `protobuf:"bytes,3,rep,name=generals" json:"generals,omitempty"`
}

func (m *CNotifyDataChange) Reset()                    { *m = CNotifyDataChange{} }
func (m *CNotifyDataChange) String() string            { return proto.CompactTextString(m) }
func (*CNotifyDataChange) ProtoMessage()               {}
func (*CNotifyDataChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CNotifyDataChange) GetChanges() []CNotifyDataChangeType {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *CNotifyDataChange) GetUser() *gamedef.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CNotifyDataChange) GetGenerals() []*gamedef.General {
	if m != nil {
		return m.Generals
	}
	return nil
}

// ===============战斗数据====================
type CReqUseSkill struct {
	SkillID uint32 `protobuf:"varint,1,opt,name=skillID" json:"skillID,omitempty"`
}

func (m *CReqUseSkill) Reset()                    { *m = CReqUseSkill{} }
func (m *CReqUseSkill) String() string            { return proto.CompactTextString(m) }
func (*CReqUseSkill) ProtoMessage()               {}
func (*CReqUseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CReqUseSkill) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

// 返回玩家数据
type CRespUseSkill struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	SkillID uint32 `protobuf:"varint,3,opt,name=skillID" json:"skillID,omitempty"`
}

func (m *CRespUseSkill) Reset()                    { *m = CRespUseSkill{} }
func (m *CRespUseSkill) String() string            { return proto.CompactTextString(m) }
func (*CRespUseSkill) ProtoMessage()               {}
func (*CRespUseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CRespUseSkill) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespUseSkill) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespUseSkill) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

type CNotifyUseSkill struct {
	UserID  uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	SkillID uint32 `protobuf:"varint,2,opt,name=skillID" json:"skillID,omitempty"`
}

func (m *CNotifyUseSkill) Reset()                    { *m = CNotifyUseSkill{} }
func (m *CNotifyUseSkill) String() string            { return proto.CompactTextString(m) }
func (*CNotifyUseSkill) ProtoMessage()               {}
func (*CNotifyUseSkill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CNotifyUseSkill) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CNotifyUseSkill) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

type CNotifyGameStart struct {
	Generals []*gamedef.GameGeneral `protobuf:"bytes,1,rep,name=generals" json:"generals,omitempty"`
}

func (m *CNotifyGameStart) Reset()                    { *m = CNotifyGameStart{} }
func (m *CNotifyGameStart) String() string            { return proto.CompactTextString(m) }
func (*CNotifyGameStart) ProtoMessage()               {}
func (*CNotifyGameStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CNotifyGameStart) GetGenerals() []*gamedef.GameGeneral {
	if m != nil {
		return m.Generals
	}
	return nil
}

type CNotifyGeneralStatus struct {
	GameGeneral *gamedef.GameGeneral `protobuf:"bytes,1,opt,name=gameGeneral" json:"gameGeneral,omitempty"`
}

func (m *CNotifyGeneralStatus) Reset()                    { *m = CNotifyGeneralStatus{} }
func (m *CNotifyGeneralStatus) String() string            { return proto.CompactTextString(m) }
func (*CNotifyGeneralStatus) ProtoMessage()               {}
func (*CNotifyGeneralStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CNotifyGeneralStatus) GetGameGeneral() *gamedef.GameGeneral {
	if m != nil {
		return m.GameGeneral
	}
	return nil
}

type CNotifyGameStage struct {
	Stage    gamedef.GameStageTyp `protobuf:"varint,1,opt,name=stage,enum=gamedef.GameStageTyp" json:"stage,omitempty"`
	LastTime int32                `protobuf:"varint,2,opt,name=lastTime" json:"lastTime,omitempty"`
}

func (m *CNotifyGameStage) Reset()                    { *m = CNotifyGameStage{} }
func (m *CNotifyGameStage) String() string            { return proto.CompactTextString(m) }
func (*CNotifyGameStage) ProtoMessage()               {}
func (*CNotifyGameStage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CNotifyGameStage) GetStage() gamedef.GameStageTyp {
	if m != nil {
		return m.Stage
	}
	return gamedef.GameStageTyp_GSTInvalid
}

func (m *CNotifyGameStage) GetLastTime() int32 {
	if m != nil {
		return m.LastTime
	}
	return 0
}

type CNotifyGameResult struct {
	Winner uint64 `protobuf:"varint,1,opt,name=winner" json:"winner,omitempty"`
	Exp    int32  `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
}

func (m *CNotifyGameResult) Reset()                    { *m = CNotifyGameResult{} }
func (m *CNotifyGameResult) String() string            { return proto.CompactTextString(m) }
func (*CNotifyGameResult) ProtoMessage()               {}
func (*CNotifyGameResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CNotifyGameResult) GetWinner() uint64 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *CNotifyGameResult) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

// ===============Game数据====================
// 创建角色
type CReqUserInit struct {
	NickName     string `protobuf:"bytes,1,opt,name=nickName" json:"nickName,omitempty"`
	FirstGeneral uint32 `protobuf:"varint,2,opt,name=firstGeneral" json:"firstGeneral,omitempty"`
}

func (m *CReqUserInit) Reset()                    { *m = CReqUserInit{} }
func (m *CReqUserInit) String() string            { return proto.CompactTextString(m) }
func (*CReqUserInit) ProtoMessage()               {}
func (*CReqUserInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *CReqUserInit) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CReqUserInit) GetFirstGeneral() uint32 {
	if m != nil {
		return m.FirstGeneral
	}
	return 0
}

type CRespUserInit struct {
	ErrCode      uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg       string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	NickName     string `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	FirstGeneral uint32 `protobuf:"varint,4,opt,name=firstGeneral" json:"firstGeneral,omitempty"`
}

func (m *CRespUserInit) Reset()                    { *m = CRespUserInit{} }
func (m *CRespUserInit) String() string            { return proto.CompactTextString(m) }
func (*CRespUserInit) ProtoMessage()               {}
func (*CRespUserInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *CRespUserInit) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespUserInit) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CRespUserInit) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CRespUserInit) GetFirstGeneral() uint32 {
	if m != nil {
		return m.FirstGeneral
	}
	return 0
}

type CReqStageFight struct {
	StageID uint32 `protobuf:"varint,1,opt,name=stageID" json:"stageID,omitempty"`
}

func (m *CReqStageFight) Reset()                    { *m = CReqStageFight{} }
func (m *CReqStageFight) String() string            { return proto.CompactTextString(m) }
func (*CReqStageFight) ProtoMessage()               {}
func (*CReqStageFight) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *CReqStageFight) GetStageID() uint32 {
	if m != nil {
		return m.StageID
	}
	return 0
}

type CRespStageFight struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *CRespStageFight) Reset()                    { *m = CRespStageFight{} }
func (m *CRespStageFight) String() string            { return proto.CompactTextString(m) }
func (*CRespStageFight) ProtoMessage()               {}
func (*CRespStageFight) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CRespStageFight) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CRespStageFight) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*CReqSyncSystemTime)(nil), "cmsg.CReqSyncSystemTime")
	proto.RegisterType((*CRespSyncSystemTime)(nil), "cmsg.CRespSyncSystemTime")
	proto.RegisterType((*CReqAuth)(nil), "cmsg.CReqAuth")
	proto.RegisterType((*CRespAuth)(nil), "cmsg.CRespAuth")
	proto.RegisterType((*CNotifyLoginInfo)(nil), "cmsg.CNotifyLoginInfo")
	proto.RegisterType((*CReqLogin)(nil), "cmsg.CReqLogin")
	proto.RegisterType((*CRespLogin)(nil), "cmsg.CRespLogin")
	proto.RegisterType((*CReqLogout)(nil), "cmsg.CReqLogout")
	proto.RegisterType((*CRespLogout)(nil), "cmsg.CRespLogout")
	proto.RegisterType((*CNotifyLogout)(nil), "cmsg.CNotifyLogout")
	proto.RegisterType((*CReqNotifyUserData)(nil), "cmsg.CReqNotifyUserData")
	proto.RegisterType((*CRespNotifyUserData)(nil), "cmsg.CRespNotifyUserData")
	proto.RegisterType((*CNotifyDataChange)(nil), "cmsg.CNotifyDataChange")
	proto.RegisterType((*CReqUseSkill)(nil), "cmsg.CReqUseSkill")
	proto.RegisterType((*CRespUseSkill)(nil), "cmsg.CRespUseSkill")
	proto.RegisterType((*CNotifyUseSkill)(nil), "cmsg.CNotifyUseSkill")
	proto.RegisterType((*CNotifyGameStart)(nil), "cmsg.CNotifyGameStart")
	proto.RegisterType((*CNotifyGeneralStatus)(nil), "cmsg.CNotifyGeneralStatus")
	proto.RegisterType((*CNotifyGameStage)(nil), "cmsg.CNotifyGameStage")
	proto.RegisterType((*CNotifyGameResult)(nil), "cmsg.CNotifyGameResult")
	proto.RegisterType((*CReqUserInit)(nil), "cmsg.CReqUserInit")
	proto.RegisterType((*CRespUserInit)(nil), "cmsg.CRespUserInit")
	proto.RegisterType((*CReqStageFight)(nil), "cmsg.CReqStageFight")
	proto.RegisterType((*CRespStageFight)(nil), "cmsg.CRespStageFight")
	proto.RegisterEnum("cmsg.CNotifyDataChangeType", CNotifyDataChangeType_name, CNotifyDataChangeType_value)
}

func init() { proto.RegisterFile("cmsg/client_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5f, 0x8f, 0x1b, 0x35,
	0x10, 0x67, 0xb3, 0xc9, 0xdd, 0x65, 0x72, 0x49, 0x83, 0xb9, 0x56, 0xa1, 0xaa, 0x50, 0x30, 0x2f,
	0x11, 0xa0, 0x04, 0x52, 0xa9, 0xa8, 0x12, 0x08, 0x9d, 0x36, 0x50, 0x45, 0x2a, 0xf7, 0xe0, 0xa4,
	0x4f, 0x15, 0xaa, 0xb6, 0x1b, 0x67, 0xcf, 0xba, 0x5d, 0xef, 0x9e, 0xed, 0xed, 0x5d, 0x1e, 0xf9,
	0x1a, 0xf0, 0xc8, 0x27, 0xe2, 0x1b, 0x21, 0xcf, 0xfe, 0x4d, 0x7b, 0x07, 0x4a, 0x9f, 0x32, 0x33,
	0x1e, 0xff, 0xfc, 0x9b, 0xdf, 0x8c, 0xbd, 0x81, 0x87, 0x41, 0xac, 0xc3, 0x59, 0x10, 0x09, 0x2e,
	0xcd, 0x9b, 0x58, 0x87, 0xd3, 0x54, 0x25, 0x26, 0x21, 0x6d, 0x1b, 0x7e, 0xfc, 0x32, 0x14, 0xe6,
	0x32, 0x7b, 0x3b, 0x0d, 0x92, 0x78, 0x76, 0xc3, 0xe5, 0xad, 0xc8, 0xe6, 0xdf, 0x3f, 0x7f, 0x3e,
	0x0b, 0xfd, 0x98, 0x6b, 0xae, 0xde, 0x71, 0x35, 0xd3, 0x2a, 0x98, 0x15, 0xa6, 0x8d, 0xe2, 0x66,
	0xb4, 0x36, 0x7c, 0x8b, 0xbf, 0x6f, 0x36, 0x7c, 0x9b, 0x63, 0xd2, 0x39, 0x10, 0x8f, 0xf1, 0xeb,
	0xd5, 0x4e, 0x06, 0xab, 0x9d, 0x36, 0x3c, 0x5e, 0x8b, 0x98, 0x93, 0x27, 0xd0, 0x35, 0x22, 0xe6,
	0xda, 0xf8, 0x71, 0x3a, 0x72, 0xc6, 0xce, 0xc4, 0x65, 0x75, 0x80, 0xfe, 0x0e, 0x9f, 0x79, 0x8c,
	0xeb, 0xf4, 0x90, 0x4d, 0x64, 0x02, 0x0f, 0x72, 0x4e, 0xeb, 0x2a, 0xa7, 0x85, 0x39, 0xef, 0x87,
	0xe9, 0x35, 0x9c, 0x58, 0x4a, 0xe7, 0x99, 0xb9, 0x24, 0x23, 0x38, 0xf6, 0x83, 0x20, 0xc9, 0xa4,
	0x41, 0xc4, 0x2e, 0x2b, 0x5d, 0xf2, 0x18, 0x4e, 0x52, 0x5f, 0xeb, 0x9b, 0x44, 0x6d, 0x10, 0xa8,
	0xcb, 0x2a, 0x9f, 0xcc, 0xa0, 0xc3, 0x6f, 0x8d, 0xf2, 0x47, 0xee, 0xd8, 0x99, 0xf4, 0xe6, 0x9f,
	0x4f, 0x8b, 0xe2, 0xa7, 0xbf, 0xd8, 0xe8, 0x79, 0x8e, 0xb0, 0x94, 0xdb, 0x84, 0xe5, 0x79, 0xf4,
	0x6f, 0x07, 0xba, 0x58, 0x52, 0x79, 0x28, 0x57, 0xca, 0x4b, 0x36, 0x1c, 0x0f, 0xed, 0xb3, 0xd2,
	0x25, 0x8f, 0xe0, 0x88, 0x2b, 0xf5, 0x9b, 0x0e, 0x8b, 0x23, 0x0b, 0xaf, 0x49, 0xd3, 0xdd, 0xa7,
	0xf9, 0x08, 0x8e, 0x32, 0xcd, 0xd5, 0x72, 0x31, 0x6a, 0x8f, 0x9d, 0x49, 0x9b, 0x15, 0x1e, 0x21,
	0xd0, 0xd6, 0x22, 0x94, 0xa3, 0x0e, 0xa6, 0xa3, 0x4d, 0xbe, 0x00, 0xc8, 0x64, 0x94, 0x04, 0x57,
	0x56, 0x8b, 0xd1, 0x11, 0xaa, 0xd3, 0x88, 0xd0, 0x1f, 0x61, 0xe8, 0x5d, 0x24, 0x46, 0x6c, 0x77,
	0x2f, 0x93, 0x50, 0x48, 0x5b, 0xc0, 0x7f, 0x08, 0x34, 0x80, 0x96, 0x48, 0x0b, 0x9e, 0x2d, 0x91,
	0xd2, 0x1f, 0xb0, 0xc4, 0x6b, 0xdc, 0xda, 0xa0, 0xe5, 0xdc, 0x49, 0xab, 0x55, 0xd3, 0xa2, 0x7f,
	0x39, 0x00, 0x28, 0x4e, 0xbe, 0xf5, 0x70, 0x75, 0xea, 0xc3, 0xdc, 0xbd, 0xc3, 0xbe, 0x84, 0xb6,
	0xb5, 0x50, 0x99, 0xde, 0xbc, 0x5f, 0x75, 0xe9, 0x95, 0xe6, 0x8a, 0xe1, 0x12, 0x19, 0x43, 0x4f,
	0x68, 0xc6, 0x83, 0x44, 0x4a, 0x1e, 0x18, 0x54, 0xeb, 0x84, 0x35, 0x43, 0xf4, 0x14, 0xc9, 0xd9,
	0xb2, 0x92, 0xcc, 0xd0, 0x9f, 0xa1, 0x57, 0x52, 0x4d, 0x32, 0x73, 0x38, 0x57, 0x7a, 0x0e, 0xfd,
	0x5a, 0x63, 0x0b, 0xf1, 0x1d, 0x74, 0xa3, 0x52, 0x6d, 0x04, 0xe9, 0xcd, 0x49, 0xc5, 0xb4, 0xea,
	0x03, 0xab, 0x93, 0xe8, 0x59, 0x7e, 0xa5, 0x72, 0x14, 0x5b, 0xcb, 0xc2, 0x37, 0x3e, 0xfd, 0xd3,
	0x29, 0x6e, 0xcd, 0x7e, 0xfc, 0x23, 0xe4, 0xfc, 0x16, 0x4e, 0x42, 0x2e, 0xb9, 0xf2, 0x23, 0x3d,
	0x72, 0xc7, 0xee, 0xa4, 0x37, 0x1f, 0x56, 0x84, 0x5e, 0xe4, 0x0b, 0xac, 0xca, 0x20, 0x5f, 0x41,
	0x67, 0x69, 0x78, 0xac, 0x47, 0x6d, 0x4c, 0xad, 0x55, 0xb6, 0x51, 0x96, 0xaf, 0xd1, 0x7f, 0x1c,
	0xf8, 0xb4, 0x28, 0xdb, 0x92, 0xf2, 0x2e, 0x7d, 0x19, 0x72, 0xf2, 0x0c, 0x8e, 0x03, 0xb4, 0xf4,
	0xc8, 0x19, 0xbb, 0x93, 0xc1, 0xfc, 0xc9, 0xd4, 0xbe, 0x40, 0xd3, 0x0f, 0x32, 0xa7, 0x66, 0x97,
	0x72, 0x56, 0x26, 0x57, 0x7d, 0x6d, 0xdd, 0xdf, 0xd7, 0x83, 0x6a, 0xa0, 0x4f, 0xa1, 0x6d, 0x4f,
	0x20, 0x03, 0x80, 0x85, 0xb7, 0x5e, 0xca, 0x77, 0x7e, 0x24, 0x36, 0xc3, 0x4f, 0x48, 0x0f, 0x8e,
	0x17, 0xde, 0xda, 0xc2, 0x0e, 0x9d, 0x62, 0xb1, 0xd8, 0x3c, 0x6c, 0xd1, 0x09, 0x9c, 0xda, 0x36,
	0xbc, 0xd2, 0x7c, 0x75, 0x25, 0xa2, 0xc8, 0x0a, 0xad, 0xad, 0x51, 0xcc, 0x7c, 0x9f, 0x95, 0x2e,
	0x7d, 0x0d, 0x7d, 0xec, 0x4c, 0x33, 0xf5, 0xf0, 0x07, 0xa0, 0x04, 0x77, 0xf7, 0xc1, 0x3d, 0x78,
	0xe0, 0x55, 0x2d, 0xcf, 0xe1, 0xef, 0xbb, 0x7c, 0x0d, 0x90, 0xd6, 0x3e, 0xc8, 0xa2, 0xba, 0xf9,
	0x2f, 0xfc, 0x98, 0xaf, 0x8c, 0xaf, 0xec, 0x60, 0xd6, 0x12, 0x3a, 0x28, 0xe1, 0x59, 0x2d, 0xa1,
	0x1f, 0xf3, 0x0f, 0x65, 0xbc, 0x80, 0xb3, 0x12, 0x25, 0x0f, 0xad, 0x8c, 0x6f, 0x32, 0x4d, 0x9e,
	0x41, 0x2f, 0xac, 0x37, 0x14, 0x43, 0x7e, 0x37, 0x58, 0x33, 0x91, 0xbe, 0x7e, 0x9f, 0x55, 0xc8,
	0xc9, 0x37, 0xd0, 0xd1, 0xd6, 0x40, 0x94, 0xc1, 0xfc, 0xe1, 0x1e, 0x0a, 0xa6, 0xac, 0x77, 0x29,
	0xcb, 0x73, 0xec, 0x1b, 0x1e, 0xf9, 0xda, 0xe0, 0x73, 0x67, 0x2b, 0xee, 0xb0, 0xca, 0xa7, 0x3f,
	0x55, 0x13, 0x69, 0x77, 0x32, 0xae, 0xb3, 0x08, 0x5f, 0xd3, 0x1b, 0x21, 0x25, 0x57, 0xa5, 0x72,
	0xb9, 0x47, 0x86, 0xe0, 0xf2, 0xdb, 0xb4, 0xc0, 0xb0, 0x26, 0xbd, 0xa8, 0xba, 0xaf, 0x96, 0x52,
	0xe0, 0xe7, 0x42, 0x8a, 0xe0, 0xea, 0xc2, 0x8f, 0x79, 0xf1, 0x50, 0x56, 0x3e, 0xa1, 0x70, 0xba,
	0x15, 0x4a, 0x9b, 0x52, 0x80, 0x5c, 0xfc, 0xbd, 0x18, 0xfd, 0xc3, 0xa9, 0x87, 0x24, 0x47, 0x3c,
	0x7c, 0x48, 0x9a, 0x1c, 0xdc, 0xff, 0xe1, 0xd0, 0xbe, 0x83, 0xc3, 0xd7, 0x30, 0xc0, 0x6f, 0xb5,
	0xd5, 0xee, 0x57, 0x11, 0x5e, 0x22, 0x07, 0x54, 0xb2, 0x31, 0xd3, 0xb9, 0x8b, 0x63, 0x87, 0xdf,
	0xe8, 0xbd, 0xe4, 0xc3, 0x08, 0xbf, 0x3d, 0xc2, 0xff, 0x08, 0x4f, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0x90, 0x71, 0xc3, 0x90, 0x08, 0x00, 0x00,
}
