// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameconf/game_base_config.proto

/*
Package gameconf is a generated protocol buffer package.

It is generated from these files:
	gameconf/game_base_config.proto
	gameconf/game_type.proto

It has these top-level messages:
	GameBaseConfig
	GlobalconfDefine
	SkillEffect
	SkillConfDefine
	SkillEffectConfDefine
	Learn
	GeneralConfDefine
	DoNotUseThis
	DoNotUseThisDefine
*/
package gameconf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Defined in table: GameBaseConfig
type GameBaseConfig struct {
	DoNotUseThis    []*DoNotUseThisDefine    `protobuf:"bytes,1,rep,name=DoNotUseThis" json:"DoNotUseThis,omitempty"`
	Globalconf      []*GlobalconfDefine      `protobuf:"bytes,2,rep,name=Globalconf" json:"Globalconf,omitempty"`
	SkillConf       []*SkillConfDefine       `protobuf:"bytes,3,rep,name=SkillConf" json:"SkillConf,omitempty"`
	SkillEffectConf []*SkillEffectConfDefine `protobuf:"bytes,4,rep,name=SkillEffectConf" json:"SkillEffectConf,omitempty"`
	GeneralConf     []*GeneralConfDefine     `protobuf:"bytes,5,rep,name=GeneralConf" json:"GeneralConf,omitempty"`
}

func (m *GameBaseConfig) Reset()                    { *m = GameBaseConfig{} }
func (m *GameBaseConfig) String() string            { return proto.CompactTextString(m) }
func (*GameBaseConfig) ProtoMessage()               {}
func (*GameBaseConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GameBaseConfig) GetDoNotUseThis() []*DoNotUseThisDefine {
	if m != nil {
		return m.DoNotUseThis
	}
	return nil
}

func (m *GameBaseConfig) GetGlobalconf() []*GlobalconfDefine {
	if m != nil {
		return m.Globalconf
	}
	return nil
}

func (m *GameBaseConfig) GetSkillConf() []*SkillConfDefine {
	if m != nil {
		return m.SkillConf
	}
	return nil
}

func (m *GameBaseConfig) GetSkillEffectConf() []*SkillEffectConfDefine {
	if m != nil {
		return m.SkillEffectConf
	}
	return nil
}

func (m *GameBaseConfig) GetGeneralConf() []*GeneralConfDefine {
	if m != nil {
		return m.GeneralConf
	}
	return nil
}

// Defined in table: Globalconf
type GlobalconfDefine struct {
	UserInitGeneral []uint32 `protobuf:"varint,1,rep,packed,name=UserInitGeneral" json:"UserInitGeneral,omitempty"`
}

func (m *GlobalconfDefine) Reset()                    { *m = GlobalconfDefine{} }
func (m *GlobalconfDefine) String() string            { return proto.CompactTextString(m) }
func (*GlobalconfDefine) ProtoMessage()               {}
func (*GlobalconfDefine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GlobalconfDefine) GetUserInitGeneral() []uint32 {
	if m != nil {
		return m.UserInitGeneral
	}
	return nil
}

// Defined in table: SkillConf
type SkillEffect struct {
	// 效果对象
	Object SkillEffectObjectTyp `protobuf:"varint,1,opt,name=Object,enum=gameconf.SkillEffectObjectTyp" json:"Object,omitempty"`
	// 最短持续时间
	Min int32 `protobuf:"varint,2,opt,name=Min" json:"Min,omitempty"`
	// 最长持续时间
	Max int32 `protobuf:"varint,3,opt,name=Max" json:"Max,omitempty"`
	// 触发概率
	Chance int32 `protobuf:"varint,4,opt,name=Chance" json:"Chance,omitempty"`
	// 等级
	Power int32 `protobuf:"varint,5,opt,name=Power" json:"Power,omitempty"`
	// 效果ID
	Id uint32 `protobuf:"varint,6,opt,name=Id" json:"Id,omitempty"`
}

func (m *SkillEffect) Reset()                    { *m = SkillEffect{} }
func (m *SkillEffect) String() string            { return proto.CompactTextString(m) }
func (*SkillEffect) ProtoMessage()               {}
func (*SkillEffect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SkillEffect) GetObject() SkillEffectObjectTyp {
	if m != nil {
		return m.Object
	}
	return SkillEffectObjectTyp_SEOTInvalid
}

func (m *SkillEffect) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *SkillEffect) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *SkillEffect) GetChance() int32 {
	if m != nil {
		return m.Chance
	}
	return 0
}

func (m *SkillEffect) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *SkillEffect) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Defined in table: SkillConf
type SkillConfDefine struct {
	SkillID         uint32         `protobuf:"varint,1,opt,name=SkillID" json:"SkillID,omitempty"`
	SkillName       string         `protobuf:"bytes,2,opt,name=SkillName" json:"SkillName,omitempty"`
	SkillType       SkillTyp       `protobuf:"varint,3,opt,name=SkillType,enum=gameconf.SkillTyp" json:"SkillType,omitempty"`
	SkillAttackType SkillAttackTyp `protobuf:"varint,4,opt,name=SkillAttackType,enum=gameconf.SkillAttackTyp" json:"SkillAttackType,omitempty"`
	Power           uint32         `protobuf:"varint,5,opt,name=Power" json:"Power,omitempty"`
	Effect          []*SkillEffect `protobuf:"bytes,6,rep,name=Effect" json:"Effect,omitempty"`
}

func (m *SkillConfDefine) Reset()                    { *m = SkillConfDefine{} }
func (m *SkillConfDefine) String() string            { return proto.CompactTextString(m) }
func (*SkillConfDefine) ProtoMessage()               {}
func (*SkillConfDefine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SkillConfDefine) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

func (m *SkillConfDefine) GetSkillName() string {
	if m != nil {
		return m.SkillName
	}
	return ""
}

func (m *SkillConfDefine) GetSkillType() SkillTyp {
	if m != nil {
		return m.SkillType
	}
	return SkillTyp_STInvalid
}

func (m *SkillConfDefine) GetSkillAttackType() SkillAttackTyp {
	if m != nil {
		return m.SkillAttackType
	}
	return SkillAttackTyp_SATInvliad
}

func (m *SkillConfDefine) GetPower() uint32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *SkillConfDefine) GetEffect() []*SkillEffect {
	if m != nil {
		return m.Effect
	}
	return nil
}

// Defined in table: SkillEffectConf
type SkillEffectConfDefine struct {
	SkillEffectID   uint32         `protobuf:"varint,1,opt,name=SkillEffectID" json:"SkillEffectID,omitempty"`
	SkillName       string         `protobuf:"bytes,2,opt,name=SkillName" json:"SkillName,omitempty"`
	SkillEffectType SkillEffectTyp `protobuf:"varint,3,opt,name=SkillEffectType,enum=gameconf.SkillEffectTyp" json:"SkillEffectType,omitempty"`
	LevelUp         int32          `protobuf:"varint,4,opt,name=LevelUp" json:"LevelUp,omitempty"`
}

func (m *SkillEffectConfDefine) Reset()                    { *m = SkillEffectConfDefine{} }
func (m *SkillEffectConfDefine) String() string            { return proto.CompactTextString(m) }
func (*SkillEffectConfDefine) ProtoMessage()               {}
func (*SkillEffectConfDefine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SkillEffectConfDefine) GetSkillEffectID() uint32 {
	if m != nil {
		return m.SkillEffectID
	}
	return 0
}

func (m *SkillEffectConfDefine) GetSkillName() string {
	if m != nil {
		return m.SkillName
	}
	return ""
}

func (m *SkillEffectConfDefine) GetSkillEffectType() SkillEffectTyp {
	if m != nil {
		return m.SkillEffectType
	}
	return SkillEffectTyp_SETInvliad
}

func (m *SkillEffectConfDefine) GetLevelUp() int32 {
	if m != nil {
		return m.LevelUp
	}
	return 0
}

// Defined in table: GeneralConf
type Learn struct {
	// 等级
	Level uint32 `protobuf:"varint,1,opt,name=Level" json:"Level,omitempty"`
	// 技能
	SkillID uint32 `protobuf:"varint,2,opt,name=SkillID" json:"SkillID,omitempty"`
}

func (m *Learn) Reset()                    { *m = Learn{} }
func (m *Learn) String() string            { return proto.CompactTextString(m) }
func (*Learn) ProtoMessage()               {}
func (*Learn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Learn) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Learn) GetSkillID() uint32 {
	if m != nil {
		return m.SkillID
	}
	return 0
}

// Defined in table: GeneralConf
type GeneralConfDefine struct {
	GeneralID   uint32   `protobuf:"varint,1,opt,name=GeneralID" json:"GeneralID,omitempty"`
	GeneralName string   `protobuf:"bytes,2,opt,name=GeneralName" json:"GeneralName,omitempty"`
	Nature      SkillTyp `protobuf:"varint,3,opt,name=Nature,enum=gameconf.SkillTyp" json:"Nature,omitempty"`
	Hp          int32    `protobuf:"varint,4,opt,name=Hp" json:"Hp,omitempty"`
	Atk         int32    `protobuf:"varint,5,opt,name=Atk" json:"Atk,omitempty"`
	Def         int32    `protobuf:"varint,6,opt,name=Def" json:"Def,omitempty"`
	Satk        int32    `protobuf:"varint,7,opt,name=Satk" json:"Satk,omitempty"`
	Sdef        int32    `protobuf:"varint,8,opt,name=Sdef" json:"Sdef,omitempty"`
	Spd         int32    `protobuf:"varint,9,opt,name=Spd" json:"Spd,omitempty"`
	LearnSkills []*Learn `protobuf:"bytes,10,rep,name=LearnSkills" json:"LearnSkills,omitempty"`
	BaseSkills  []uint32 `protobuf:"varint,11,rep,packed,name=BaseSkills" json:"BaseSkills,omitempty"`
}

func (m *GeneralConfDefine) Reset()                    { *m = GeneralConfDefine{} }
func (m *GeneralConfDefine) String() string            { return proto.CompactTextString(m) }
func (*GeneralConfDefine) ProtoMessage()               {}
func (*GeneralConfDefine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GeneralConfDefine) GetGeneralID() uint32 {
	if m != nil {
		return m.GeneralID
	}
	return 0
}

func (m *GeneralConfDefine) GetGeneralName() string {
	if m != nil {
		return m.GeneralName
	}
	return ""
}

func (m *GeneralConfDefine) GetNature() SkillTyp {
	if m != nil {
		return m.Nature
	}
	return SkillTyp_STInvalid
}

func (m *GeneralConfDefine) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *GeneralConfDefine) GetAtk() int32 {
	if m != nil {
		return m.Atk
	}
	return 0
}

func (m *GeneralConfDefine) GetDef() int32 {
	if m != nil {
		return m.Def
	}
	return 0
}

func (m *GeneralConfDefine) GetSatk() int32 {
	if m != nil {
		return m.Satk
	}
	return 0
}

func (m *GeneralConfDefine) GetSdef() int32 {
	if m != nil {
		return m.Sdef
	}
	return 0
}

func (m *GeneralConfDefine) GetSpd() int32 {
	if m != nil {
		return m.Spd
	}
	return 0
}

func (m *GeneralConfDefine) GetLearnSkills() []*Learn {
	if m != nil {
		return m.LearnSkills
	}
	return nil
}

func (m *GeneralConfDefine) GetBaseSkills() []uint32 {
	if m != nil {
		return m.BaseSkills
	}
	return nil
}

func init() {
	proto.RegisterType((*GameBaseConfig)(nil), "gameconf.GameBaseConfig")
	proto.RegisterType((*GlobalconfDefine)(nil), "gameconf.GlobalconfDefine")
	proto.RegisterType((*SkillEffect)(nil), "gameconf.SkillEffect")
	proto.RegisterType((*SkillConfDefine)(nil), "gameconf.SkillConfDefine")
	proto.RegisterType((*SkillEffectConfDefine)(nil), "gameconf.SkillEffectConfDefine")
	proto.RegisterType((*Learn)(nil), "gameconf.Learn")
	proto.RegisterType((*GeneralConfDefine)(nil), "gameconf.GeneralConfDefine")
}

func init() { proto.RegisterFile("gameconf/game_base_config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xd1, 0x6e, 0xd3, 0x4a,
	0x10, 0x95, 0x9d, 0xc4, 0x6d, 0x27, 0x37, 0x69, 0xef, 0x88, 0xa2, 0xa5, 0x54, 0x6d, 0x64, 0xf1,
	0x10, 0x21, 0x51, 0xa0, 0x48, 0x54, 0x42, 0x20, 0xd1, 0x36, 0xa8, 0x8d, 0x54, 0x0a, 0x72, 0xda,
	0xe7, 0x6a, 0x13, 0xaf, 0x5b, 0x93, 0xd4, 0xb6, 0x6c, 0x03, 0xcd, 0x3b, 0xff, 0xc2, 0x37, 0xf0,
	0xc6, 0x2f, 0xf0, 0x47, 0x68, 0xc7, 0xeb, 0xec, 0xda, 0x44, 0xf0, 0xb6, 0x73, 0xe6, 0x9c, 0xf5,
	0x9c, 0x99, 0x59, 0xc3, 0xee, 0x35, 0xbf, 0x15, 0x93, 0x38, 0x0a, 0x9e, 0xca, 0xc3, 0xd5, 0x98,
	0x67, 0xe2, 0x4a, 0x86, 0xe1, 0xf5, 0x5e, 0x92, 0xc6, 0x79, 0x8c, 0xab, 0x25, 0x61, 0x8b, 0x55,
	0xa9, 0xf9, 0x3c, 0x11, 0x05, 0xc7, 0xfd, 0x65, 0x43, 0xf7, 0x84, 0xdf, 0x8a, 0x23, 0x9e, 0x89,
	0x63, 0x12, 0xe3, 0x5b, 0xf8, 0x6f, 0x10, 0x9f, 0xc7, 0xf9, 0x65, 0x26, 0x2e, 0x6e, 0xc2, 0x8c,
	0x59, 0xbd, 0x46, 0xbf, 0xbd, 0xbf, 0xbd, 0x57, 0xde, 0xb1, 0x67, 0x66, 0x07, 0x22, 0x08, 0x23,
	0xe1, 0x55, 0x14, 0xf8, 0x0a, 0xe0, 0x64, 0x16, 0x8f, 0xf9, 0x4c, 0xd2, 0x99, 0x4d, 0xfa, 0x2d,
	0xad, 0xd7, 0x39, 0xa5, 0x36, 0xd8, 0x78, 0x00, 0x6b, 0xa3, 0x69, 0x38, 0x9b, 0xc9, 0x62, 0x58,
	0x83, 0xa4, 0x0f, 0xb4, 0x74, 0x91, 0x52, 0x4a, 0xcd, 0xc5, 0x21, 0xac, 0x53, 0xf0, 0x2e, 0x08,
	0xc4, 0x24, 0x27, 0x79, 0x93, 0xe4, 0xbb, 0x35, 0xb9, 0x26, 0xa8, 0x4b, 0xea, 0x3a, 0x7c, 0x03,
	0xed, 0x13, 0x11, 0x89, 0x94, 0x17, 0x55, 0xb4, 0xe8, 0x9a, 0x87, 0x86, 0x01, 0x9d, 0x54, 0x57,
	0x98, 0x7c, 0xf7, 0x35, 0x6c, 0xd4, 0x2d, 0x62, 0x1f, 0xd6, 0x2f, 0x33, 0x91, 0x0e, 0xa3, 0x30,
	0x57, 0x54, 0xea, 0x6b, 0xc7, 0xab, 0xc3, 0xee, 0x77, 0x0b, 0xda, 0x46, 0x41, 0xf8, 0x12, 0x9c,
	0x0f, 0xe3, 0x4f, 0x62, 0x92, 0x33, 0xab, 0x67, 0xf5, 0xbb, 0xfb, 0x3b, 0x4b, 0xed, 0x14, 0x94,
	0x8b, 0x79, 0xe2, 0x29, 0x36, 0x6e, 0x40, 0xe3, 0x7d, 0x18, 0x31, 0xbb, 0x67, 0xf5, 0x5b, 0x9e,
	0x3c, 0x12, 0xc2, 0xef, 0x58, 0x43, 0x21, 0xfc, 0x0e, 0xef, 0x83, 0x73, 0x7c, 0xc3, 0xa3, 0x89,
	0x60, 0x4d, 0x02, 0x55, 0x84, 0xf7, 0xa0, 0xf5, 0x31, 0xfe, 0x2a, 0x52, 0xd6, 0x22, 0xb8, 0x08,
	0xb0, 0x0b, 0xf6, 0xd0, 0x67, 0x4e, 0xcf, 0xea, 0x77, 0x3c, 0x7b, 0xe8, 0xbb, 0xdf, 0x6c, 0xd5,
	0x72, 0xdd, 0x08, 0x64, 0xb0, 0x42, 0xd0, 0x70, 0x40, 0xe5, 0x76, 0xbc, 0x32, 0xc4, 0x6d, 0x35,
	0xd8, 0x73, 0x7e, 0x2b, 0xa8, 0xaa, 0x35, 0x4f, 0x03, 0xf8, 0x4c, 0x65, 0x2f, 0xe6, 0x89, 0xa0,
	0x0a, 0xbb, 0xfb, 0x58, 0x33, 0x2a, 0xcd, 0x69, 0x12, 0x1e, 0xa9, 0x8f, 0x1f, 0xe6, 0x39, 0x9f,
	0x4c, 0x49, 0xd7, 0x24, 0x1d, 0xab, 0xe9, 0x16, 0x04, 0xaf, 0x2e, 0xa8, 0xfa, 0xec, 0x94, 0x3e,
	0x9f, 0x80, 0x53, 0x34, 0x95, 0x39, 0x34, 0xf9, 0xcd, 0xa5, 0x1d, 0xf7, 0x14, 0xc9, 0xfd, 0x61,
	0xc1, 0xe6, 0xd2, 0xc5, 0xc2, 0x47, 0xd0, 0x31, 0x12, 0x8b, 0x96, 0x54, 0xc1, 0x7f, 0x34, 0xe6,
	0xa8, 0xb2, 0xd6, 0x46, 0x7b, 0xd8, 0xd2, 0xaa, 0xb4, 0x4d, 0x2d, 0x90, 0x43, 0x39, 0x13, 0x5f,
	0xc4, 0xec, 0x32, 0x51, 0x73, 0x2e, 0x43, 0xf7, 0x00, 0x5a, 0x67, 0x82, 0xa7, 0x91, 0xec, 0x04,
	0x61, 0xaa, 0xc4, 0x22, 0x30, 0xa7, 0x69, 0x57, 0xa6, 0xe9, 0xfe, 0xb4, 0xe1, 0xff, 0x3f, 0x9e,
	0x81, 0xb4, 0xa2, 0xc0, 0x85, 0x59, 0x0d, 0x60, 0x6f, 0xf1, 0xac, 0x0c, 0xab, 0x26, 0x84, 0x8f,
	0xc1, 0x39, 0xe7, 0xf9, 0xe7, 0xf4, 0x6f, 0x2b, 0xa0, 0x18, 0x72, 0x1b, 0x4f, 0x4b, 0x3f, 0xf6,
	0x69, 0x22, 0xb7, 0xfb, 0x30, 0x9f, 0xaa, 0x8d, 0x95, 0x47, 0x89, 0x0c, 0x44, 0x40, 0x0b, 0xdb,
	0xf2, 0xe4, 0x11, 0x11, 0x9a, 0x23, 0x9e, 0x4f, 0xd9, 0x0a, 0x41, 0x74, 0x26, 0xcc, 0x17, 0x01,
	0x5b, 0x55, 0x98, 0x2f, 0x02, 0xa9, 0x1c, 0x25, 0x3e, 0x5b, 0x2b, 0x94, 0xa3, 0xc4, 0xc7, 0xe7,
	0xd0, 0xa6, 0x46, 0x51, 0x19, 0x19, 0x03, 0x5a, 0x8c, 0x75, 0x5d, 0x1e, 0x25, 0x3d, 0x93, 0x83,
	0x3b, 0x00, 0xf2, 0xaf, 0xaa, 0x14, 0x6d, 0x7a, 0xed, 0x06, 0x32, 0x76, 0xe8, 0x0f, 0xfc, 0xe2,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x1d, 0xe8, 0x30, 0xc8, 0x05, 0x00, 0x00,
}
